### ISSUE TITLE
Additional wildcard support for add-tables and filter-tables

### ISSUE THREAD

**Issue by taylor-rolison** [eulerto/wal2json#104]
Hello, I was wondering if you would consider adding some additional wildcard support to "add-tables" / "filter-tables" params. I am working with a DB schema that has a lot of tables and activity. The tables I want to filer on get dynamically generated (basically a new partition gets created each month with the date in the name). If I use the existing wildcard functionality I will get changes for all the tables under my schema, when I just want changes from that small subset that will change over time. For example I would like to be able to just use "partitions.my_tables_20*" to get changes from every month partition that exists and will exist.

Also, I noticed that even though changes are filtered out when using "add-tables", I still get empty change messages on the slot like this:

`
{"change":[]}
`

Is this functionality intentional? It would be nice to not have those empty changes clutter up the stream or have an option to disable them.

**Comment by eulerto** [comment]
While I was designing these features, I thought about the wildcard in schema / table names but decided to not complicate the feature.

> I would like to be able to just use "partitions.my_tables_20*" to get changes from every month partition that exists and will exist.

You can add a long list of partitions in the `add-tables`. Are you sure you won't apply any bug fix during a whole year? (Then a replication restart could update your table list)

> I still get empty change messages on the slot

Are you sure it is not a transaction that contains only DDL? If it is not, provide a test case.

**Comment by taylor-rolison** [comment]
I understand if you don't want to complicate the code. We could probably get away with just manually specifying the table names.

I was just going off of the output of pg_recvlogical. The DB I am working with is full of extremely complicated legacy code, so no I'm not entirely sure what could be causing that output. I will dig a little deeper but the empty changes are not a big deal either way.

**Comment by blimmer** [comment]
@eulerto This feature would be really helpful for ignoring `pg_temp_*` tables. In my use-case, I'm seeing massive messages because of temp tables created in a transaction. However, the temp "number" at the end of the table name isn't predictable so being able to wildcard ignore it (e.g. use `public.pg_temp_*` as a parameter to `filter-tables`) would be awesome.
