### ISSUE TITLE
Messages still contain unchanged TOAST columns

### ISSUE THREAD

**Issue by gunnarmorling** [eulerto/wal2json#109]
Hi, it was my assumption that with #74 being resolved, unchanged TOAST columns would not be contained in the wal2json messages any longer. But in fact I still see them under "old-keys". Is this expected? With the removal of the "include-unchanged-toast" option, it seems there's no way to disable this, or is there?

**Comment by eulerto** [comment]
@gunnarmorling could you provide a test case?
