### ISSUE TITLE
Delete Or Clear Bad Transaction

### ISSUE THREAD

**Issue by Nerdenberger** [eulerto/wal2json#114]
Hey Folks, 
Please let me know if this is not the best place for this question and I'll remove it. (I'm desperate and this seems to be the only place to ask)  

**Is there some way to delete a specific transaction record by its LSN?**

We use wal2JSON indirectly.  We have it installed on our DB and a 3rd party tool, stitchdata, uses the slot to replicate into a data warehouse.

We have a particular transaction log that can't be consumed because of the memory limitations.

```
ERROR:  out of memory
DETAIL:  Cannot enlarge string buffer containing 1073741680 bytes by 836 more bytes.
CONTEXT:  slot "stitch", output plugin "wal2json", in the change callback, associated LSN 1100/A3A3F778
```

So the whole integration is stuck and not replicating.  We know the offending change and know we don't need it replicated into our warehouse.  Is there someway to delete that specific transaction so the replication job can continue?  We are trying to avoid dropping the slot and having to fully replicate the database back into the warehouse.

Note, since we are using a 3rd party tool we can't use the write-in-chunks option because they are not setup to parse the JSON stream.

**Comment by eulerto** [comment]
> Is there some way to delete a specific transaction record by its LSN?
No. However, if you are using postgres 11 you can advance the slot a little with function `pg_replication_slot_advance`.
