### ISSUE TITLE
Change to pg_hba.conf Configuration

### ISSUE THREAD

**Issue by zylo47** [eulerto/wal2json#118]
In the setup documentation it says to enter the following into the pg_hba.conf:

`local    replication     myuser                     trust`

It appears that in Postgres v10+ the pg_hba.conf should use the actual database name rather than the **replication** keyword.  This is documented in their release notes and I was able to verify it in my testing environment.

should read

`local    <database>     myuser                     trust`

Here's the exact quote from the release notes:

> Change how logical replication uses pg_hba.conf (Peter Eisentraut)
> 
> In previous releases, a logical replication connection required the replication keyword in the database column. As of this release, logical replication matches a normal entry with a database name or keywords such as all. Physical replication continues to use the replication keyword. Since built-in logical replication is new in this release, this change only affects users of third-party logical replication plugins.

see [postgresql v10 release notes](https://www.postgresql.org/docs/10/release-10.html)

Since I'm fairly new to this I would like someone else to confirm

**Comment by eulerto** [comment]
Fixed at commit fc4c2af215ad647e62b3ba40f60cecab527bb460
