### ISSUE TITLE
Bug with how "oldkeys" is built

### ISSUE THREAD

**Issue by rdunklau** [eulerto/wal2json#121]
Hello,

In the case of update and delete statements, the oldkeys value is built using the attnames as found in the index corresponding to the primary key. As discussed [here](https://www.postgresql.org/message-id/flat/CAA8M49rWpMuv9nOUdRPn-TPF_gBhTyU%3DShbc0%2BnOXuuL1zGjYA%40mail.gmail.com#68024f99e6df3b3eaed0148d0f66aa17) this information cannot be trusted, as it is not updated when a column is renamed.

The end result is that when trying to stream changes for a table which primary key column has been renamed, empty arrays are emitted for oldkeys and oldvalues making it impossible to replay the update / delete.

**Comment by eulerto** [comment]
it is fixed in commit 8139a6dbf1d78e62d44ab8ef0cddf186ffcc2c4e. I mentioned the wrong issue number (#11), however it should be this issue.
