### ISSUE TITLE
Decode Delete Events?

### ISSUE THREAD

**Issue by petriggles** [eulerto/wal2json#125]
I'm using `psycopg2==2.8.3` to consume a replication slot on an RDS PostgreSQL database (`11.1`). INSERT and UPDATE events come through great, but is it possible to get DELETE events? Transactions with just DELETE events generate a WAL log in the database as I can tell from a temporary bump in WAL storage, but the transactions come through w/ an empty list of events.

I can't seem to find a `wal2json`, `psycopg2`, or `posgresql` setting that references this behavior.

**Comment by eulerto** [comment]
Could you provide a test case? It seems your table doesn't have PK or REPLICA IDENTITY.

**Comment by petriggles** [comment]
Ahh, that was it! I was testing this with a scratch table that was missing a PK 🤦‍♂ Thanks!
