### ISSUE TITLE
Can I filter the "Delete" transaction? Maybe I only need "Insert","Update"

### ISSUE THREAD

**Issue by TracyGao01** [eulerto/wal2json#126]
Hello,
Can I filter the "Delete" transaction? Maybe I only need "Insert","Update",I want to lose the "Delete",I find the parameter "filter-msg-prefixes",but  I don't know if it will work.

**Comment by eulerto** [comment]
`ALTER PUBLICATION pub1 SET (publish = 'insert, update');`
