### ISSUE TITLE
Failed install on CentOS 7

### ISSUE THREAD

**Issue by ekremtoprak** [eulerto/wal2json#131]
Im having an issue installing wal2json on my centos:

[ekrem@localhost wal2json]$ USE_PGXS=1 make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o wal2json.o wal2json.c
make: gcc: Command not found
make: *** [wal2json.o] Error 127

![Screenshot from 2019-10-15 13-13-47](https://user-images.githubusercontent.com/26874669/66826819-a8801f80-ef4d-11e9-9fef-232159b79aa9.png)

**Comment by eulerto** [comment]
Install gcc compiler.

**Comment by ekremtoprak** [comment]
I installed the gcc compiler, now i get this: 

![Screenshot from 2019-10-15 13-57-48](https://user-images.githubusercontent.com/26874669/66829560-ec762300-ef53-11e9-8858-61c78fe352bf.png)

**Comment by eulerto** [comment]
Install clang compiler.
