### ISSUE TITLE
Default wal2json format

### ISSUE THREAD

**Issue by vhiairrassary** [eulerto/wal2json#139]
https://github.com/eulerto/wal2json/commit/1b0cbac484f4fe5db80445f6721957511b4de7b7 introduces a new format:
> This is a new format for wal2json. You can choose it using option 'format-version' = 2. This format is completely different from version 1.

From this, my understanding is that by default the first format it still the default, but it is not the case. It is the wanted behavior?

Linked code:
https://github.com/eulerto/wal2json/blob/1b0cbac484f4fe5db80445f6721957511b4de7b7/wal2json.c#L28 https://github.com/eulerto/wal2json/blob/1b0cbac484f4fe5db80445f6721957511b4de7b7/wal2json.c#L196)
https://github.com/eulerto/wal2json/blob/1b0cbac484f4fe5db80445f6721957511b4de7b7/wal2json.c#L475-L510

**Comment by vhiairrassary** [comment]
I have certainly missed something since even the [README.md](https://github.com/eulerto/wal2json/blob/master/README.md) mentions:
> format-version: defines which format to use. Default is 1.

**Comment by eulerto** [comment]
If you want to use old format just add 'format-version' parameter. It was introduced in commit f81bf7af09324da656be87dfd53d20741c01e1e0.

**Comment by vhiairrassary** [comment]
Thanks for the answer 👍. We had regressions in our tests as they use the latest version of wal2json. What do you think about:
- Updating the README as it still mentions `format-version: defines which format to use. Default is 1.`,
- Write a note about the breaking change in the README?

If you are ok I can write the PR. (IMHO I still think such breaking change will have rough impacts for several engineers).

**Comment by eulerto** [comment]
New releases sometimes break compatibility. Since you mentioned it, I'm not so sure the next version will have default `format-version` as 2.

**Comment by vhiairrassary** [comment]
👍About the PR I mentioned in my previous post, do you want me to do it (mention the breaking change & fix the doc. about the default format)?

**Comment by eulerto** [comment]
I adjusted it in commit 3909a51f5089be1fbd0a315e47743db61ea66be6.

**Comment by vhiairrassary** [comment]
Awesome, thanks!
