### ISSUE TITLE
License ambiguity concern

### ISSUE THREAD

**Issue by crunchyjohn** [eulerto/wal2json#141]
Hello!

I found an ambiguity with regard to the license.

Looking at the file:
https://github.com/eulerto/wal2json/blob/master/README.md
It says "wal2json is released under PostgreSQL license."
But, later, under the license in the same file, it appears to be the BSD 3-Clause license.

Additionally the file:
https://github.com/eulerto/wal2json/blob/master/LICENSE
is clearly the BSD-3 license.

Should the line "wal2json is released under PostgreSQL license" in the README.md be converted to "wal2json is released under PostgreSQL license BSD 3-Clause license"?

Which one is accurate?

**Comment by eulerto** [comment]
@crunchyjohn that's an oversight. I fixed it in commit ff20f8d90b00e9d4fba468fa115f109303c80541.
