### ISSUE TITLE
Incorrect date (timestamp) format in generated JSON

### ISSUE THREAD

**Issue by dko-slapdash** [eulerto/wal2json#144]
This is partially discussed in https://github.com/eulerto/wal2json/issues/66 , but the problem is that JSON has a pretty exact format for dates - ISO 8601:

```
> JSON.stringify({a: new Date()})
{"a":"2020-01-16T23:14:25.279Z"}
```

And PostgreSQL doesn't follow this standard in either of its default type-to-text conversions (i.e. there is no way to set ISO 8601 in `datestyle`).

What's worse is that, depending on circumstances, PostgreSQL can emit stringified dates in 3 different "fashions":

```
2015-07-28 15:47:28+01
2015-07-28 15:47:28.123+01
2015-07-28 15:47:28.123456+01
```

which e.g. doesn't let to use for their parsing some standard tools like Java's SimpleDateFormat utilized in Elasticsearch:

```
"yyyy-MM-dd HH:mm:ss.SSSX"
```

I strongly believe that the right solution here would be to teach wal2json to emit dates in strict ISO 8601 with an additional `if` in the code. Just because of the "json" suffix in "wal2json" name - it should emit a JSON with default behavior.

**Comment by rcoup** [comment]
> JSON has a pretty exact format for dates

The [JSON spec](https://www.json.org/json-en.html) doesn't specify dates _at all_. I think you're referring to Javascript's [`Date.toJSON()` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toJSON)?

ISO 8601 specifies all sorts of abominable combinations (eg: week numbering, ordinal days), and allows omitting basically any component (eg. just having a year + month, nothing else). PostgreSQL uses RFC3339 which is essentially a restricted profile of ISO8601. [Wikipedia](https://en.wikipedia.org/wiki/ISO_8601) and the [PostgreSQL](https://www.postgresql.org/docs/12/datatype-datetime.html) docs have more information.

On a more practical level, PG timestamp & time values may be naive (no timezone) or be timezone-aware too.

IME most date-parsers are ok with optional decimal seconds? (ISO8601 ones should be). AFAIK `SimpleDateTime` has been superceded by the `java.time` classes from Java8, which has better support.

**Comment by dko-slapdash** [comment]
Yes, it's all about Date.toJSON() format, this method is called by e.g. `JSON.stringify({a: new Date()})`

I understand, "to java.time or not to java.time, that is the question", but e.g. Elasticsearch is using SimpleDateTime, and it **can't** parse wal2json dates even with the following ugly format string:

```
"created_at": {
  "type": "date",
  "format": "date_optional_time||yyyy-MM-dd HH:mm:ss.SSSSSSX||yyyy-MM-dd HH:mm:ss.SSSX||yyyy-MM-dd HH:mm:ssX"
},
```

You may say that it's a question to Elasticsearch guys, should they support a more sophisticated parsing or not, but wal2json is a much smaller and much more flexible project than ES monster, plus Date.toJSON() is kinda standard too (as opposed to the Postgres timestamp format).

Currently we have to post-process records fetched from wal2json before putting them to ES just because of the above aspect with dates. And to do this post-processing, we have to hardcode the list of "date holding" fields.

**Comment by eulerto** [comment]
> wal2json is a much smaller and much more flexible project than ES monster
This argument does not hold much water. If ES can't parse a timestamp string, blame ES. I have to be convinced to add "transformation" into `wal2json` (there is always an overhead).

**Comment by dko-slapdash** [comment]
What to say here... it's pity. It seems like the things which drive wal2json design are a little bit of questions like "whom to blame" or "is it a business of wal2json or not", as opposed to "how to make the experience of wal2json users seamless, minimize the number of common mistakes and make the life easier". The former approach is commonly a trait of enterprise software, whilst the latter is typically a trait of a healthy open-source project.

**Comment by rcoup** [comment]
@dko-slapdash the [ElasticSearch mapping format docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html) says "Completely customizable date formats are supported. The syntax for these is explained [DateTimeFormatter docs](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html)." which AFAICT are quite happy with optional second fractions, and flexible timezone offsets (`offset-X`).

Looks like this might work? `yyyy-MM-dd HH.mm.ss[.SSS[SSS]]X`

**Comment by dko-slapdash** [comment]
> Looks like this might work? yyyy-MM-dd HH.mm.ss[.SSS[SSS]]X

Just for the history: @rcoup, no, that doesn’t work, as stated in an example in Jan 17th comment. There is no solution at ES side for this.
