### ISSUE TITLE
README: Clarify include-unchanged-toast usage

### ISSUE THREAD

**Issue by jmealo** [eulerto/wal2json#145]
From README.md

> `include-unchanged-toast` (deprecated): add TOAST value even if it was not modified. Since TOAST values are usually large, this option could save IO and bandwidth if it is disabled. **Default is true.**

It's unclear what the behavior is here -- if this is deprecated -- how could it default to true? Is passing false still valid usage? [if so, should this parameter be renamed to --`exclude--unchanged-toast` -- which would no longer be deprecated?]

Right now you have to trace the code, and the first usage you see makes it look like passing this in at all will output a deprecation error. I think the behavior should be clearer from the docs.

This is clearly causing confusion: #109 #96 #132

**Comment by eulerto** [comment]
Fixed in commit 0d1fb8c0fed63da8fdb1f3c0e0579b35a5ef7a6a.
