### ISSUE TITLE
Memory leak in PostgreSQL walsender process with add-tables option

### ISSUE THREAD

**Issue by haizz** [eulerto/wal2json#146]
1. Create replication slot with wal2json plugin.
2. Start streaming with `add-tables=public.tableA` option.
3. Perform many transactions with many changes to `public.tableB`.
4. wal2json outputs lots of empty change sets.
5. walsender memory usage quickly blows up never coming back.

There's no such leak when `add-tables` option is not set or changes are made to tables included in `add-tables` filter.

PostgreSQL version 12.1, wal2json version 2.0

**Comment by eulerto** [comment]
Fixed in commit fbf9505e6e2fca6003ab26009c4999a8fe66d340.
