### ISSUE TITLE
Bug in pg_decode_change_v1, "actions" parameter is not usable

### ISSUE THREAD

**Issue by dko-slapdash** [eulerto/wal2json#148]
The code below doesn't do what it was intended to do:

https://github.com/eulerto/wal2json/blob/33a272b205403d37ccad566412baf914c3559429/wal2json.c#L1122-L1140

It basically "requires ALL of actions.insert, actions.update and actions.delete be presented at the same time", no matter which actual change is received.

Easy to reproduce/test:

```
# does not catch anything
pg_recvlogical -d postgres --slot zzz --start -P wal2json -f- "add-tables=public.test" --option "actions=insert, delete"

# does catch everything
pg_recvlogical -d postgres --slot zzz --start -P wal2json -f- "add-tables=public.test" --option "actions=insert,update,delete"
```

The fix is to change the above code with the following:
```
	if (change->action == REORDER_BUFFER_CHANGE_INSERT && !data->actions.insert)
	{
		elog(DEBUG3, "ignore INSERT");
		return;
	}
	if (change->action == REORDER_BUFFER_CHANGE_UPDATE && !data->actions.update)
	{
		elog(DEBUG3, "ignore UPDATE");
		return;
	}
	if (change->action == REORDER_BUFFER_CHANGE_DELETE && !data->actions.delete)
	{
		elog(DEBUG3, "ignore DELETE");
		return;
	}
```

**Comment by dko-slapdash** [comment]
BTW, wal2json is available in all AWS Aurora instances of PostgreSQL by default. They only have v1 there, and it has this issue.

**Comment by eulerto** [comment]
Fixed. Thanks for your report!
