### ISSUE TITLE
Invalid Timestamp on include-timestamp parameter

### ISSUE THREAD

**Issue by enggarranu** [eulerto/wal2json#149]
Hi

Im geting a wrong timestamp output. 
The timestamp output from include-timestamp parameter is 2002-12-30 10:46:03.524744+07 and it is static (not changing at all)

I created slot with this command :
`pg_recvlogical -d test-db --slot test_slot --create-slot -P wal2json`

and get output with this command :
`pg_recvlogical -d test-db --slot test_slot --start -o pretty-print=1 -o include-timestamp=true -f -`

output:
```
{
	"timestamp": "2002-12-30 10:46:03.524744+07",
	"change": [
		{
			"kind": "update",
			"schema": "public",
			"table": "inbox",
			"columnnames": ["inbox_id", "last_reply_by", "last_reply_time", "last_reply_message",  "create_time",  "update_time", "shop_id"],
			"columntypes": ["bigint", "timestamp without time zone", "text", "timestamp without time zone", "timestamp without time zone", "bigint"],
			"columnvalues": [54321, "2019-10-17 19:00:56.43153", "&nbsp;tepung ketan",  "2019-07-17 21:20:33.176885", "2020-02-11 14:50:19.457752", 1234567],
			"oldkeys": {
				"keynames": ["inbox_id"],
				"keytypes": ["bigint"],
				"keyvalues": [54321]
			}
		}
	]
}
```

please help me, how to fix the timestamp on json output.
Thanks in advance.

**Comment by alexshakurin** [comment]
Hello,
Could you please provide more details on how you work with "inbox" table? Do you call somewhere `pg_replication_origin_session_setup` function to setup replication origin? 
I had a similar issue when I used `pg_replication_origin_session_setup` but didn't call `pg_replication_origin_xact_setup`.

**Comment by eulerto** [comment]
@enggarranu Could you provide `postgres` and `wal2json` version?

**Comment by enggarranu** [comment]
hi @alexshakurin 
I'm not sure about that because I never used the function

hi @eulerto 
I have tried installing it on postgres 9.6.9 and 9.6.6
for wal2json version, i don't know how to check, because step

**Comment by eulerto** [comment]
Since you don't provide a use case, I cannot reproduce it. If it is still the case for your setup, upgrade to the latest Postgres version (9.6.18 at the moment) and execute the README example. Provide the output.
