### ISSUE TITLE
Could anyone provide the data type mapping from pg to json?

### ISSUE THREAD

**Issue by congfairy** [eulerto/wal2json#150]

**Comment by congfairy** [comment]
Hi, I am working on a pg data transfer service. I use wal2json to get the increasing wal data from server, but when I got the json data from server by wal2json, I don't know if I shoud use getstring() or getint() or any other function clearly, since we have different users and different pg data type. And in the json we get by wal2json, we can only see the pg data type. Is there a data type mapping table from pg data type to json data type, then I could use rapidjson json parser to deal with it.

**Comment by congfairy** [comment]
@eulerto

**Comment by eulerto** [comment]
@congfairy Your "pg data service" should be aware of data types. `wal2json` maps Postgres data types according to JSON spec (number, string, true, false, null). Option `include-types` adds data types to JSON then you can match them and use `getXXX()`. Moreover, if your data model is fixed, you can guess which function will be used.
