### ISSUE TITLE
Old-keys returning only the id in some tables

### ISSUE THREAD

**Issue by dbtorrico** [eulerto/wal2json#152]
Hello, I'm testing the plugin using 3 different tables.
One of them (pokemon table) return this json on UPDATE:
`{'columnnames': ['id',
                 'identifier',
                 'species_id',
                 'height',
                 'weight',
                 'base_experience',
                 'order',
                 'is_default'],
 'columnvalues': [3, 'test_update', 3, 20, 1000, 236, 3, True],
 'kind': 'update',
 'oldkeys': {'keynames': ['id',
                          'identifier',
                          'species_id',
                          'height',
                          'weight',
                          'base_experience',
                          'order',
                          'is_default'],
             'keyvalues': [3, 'test', 3, 20, 1000, 236, 3, True]},
 'schema': 'public',
 'table': 'pokemon'}`

The oldkeys are returning all fields of the table, so it's easy to see that what I changed was the **identifier** by comparing the **columnvalues** with **oldkeys**.

When showing the UPDATE on other tables, this is what I got:
`{'columnnames': ['id', 'identifier', 'generation_id', 'damage_class_id'],
 'columnvalues': [1, 'test_update', 1, 2],
 'kind': 'update',
 'oldkeys': {'keynames': ['id'], 'keyvalues': [1]},
 'schema': 'public',
 'table': 'poketypes'}
`

In this case, oldkeys is displaying only the **id**, but I wanted to see all the fields, just like is showing in the pokemon table.
I created another table and the result is the same as in the poketypes table.
It seems its returning all the fields only on pokemon table.
Any clues of what might be happening?

**Comment by eulerto** [comment]
Read about REPLICA IDENTITY [1]. You should set how information is written in WAL to identify rows which are updated or deleted.

`ALTER TABLE pokemon REPLICA IDENTITY FULL`.

[1] https://www.postgresql.org/docs/12/sql-altertable.html

**Comment by dbtorrico** [comment]
Thank you so much for the fast answer and the reference!
