### ISSUE TITLE
Please make independent of VC++ redist

### ISSUE THREAD

**Issue by OfficeUnlimited** [eulerto/wal2json#154]

**Comment by eulerto** [comment]
How did you install `wal2json`? AFAICS VC++ redistributable is done by a Postgres installer. We don't even provide packages.

**Comment by OfficeUnlimited** [comment]
HI Eulerto,

I have VS2019 on my system. Building from source went fine without errors. However, when I try to use the wal2json.dll in my project (Striim, trying to use Postgres as a source, hence wal2json), I get an error setting up the replication slot:

pg_recvlogical -d test --slot striim_slot --create-slot -P wal2json -U postgres

results in:

pg_recvlogical: error: could not send replication command "CREATE_REPLICATION_SLOT "striim_slot" LOGICAL "wal2json" NOEXPORT_SNAPSHOT": ERROR:  could not load library "C:/Program Files/PostgreSQL/12/lib/wal2json.dll": The specified procedure could not be found.

The file is there, it can find the file, but it says the function is not there..

Any idea what goes wrong here? Thanks for your time btw..

Regards,
Ronald

**Comment by eulerto** [comment]
How did you installed Postgres 12 (package, source code)? Could you open `wal2json.dll` in [Dependency Walker](http://www.dependencywalker.com/) and share information here?

**Comment by OfficeUnlimited** [comment]
I installed Postgres from package (just the Windows installer).  Please find the dep walker info attached in this message... it's from my own build of course.
tx.

[dep_walker_wal2json.zip](https://github.com/eulerto/wal2json/files/4307645/dep_walker_wal2json.zip)

**Comment by OfficeUnlimited** [comment]
Hi Eulerto, Any updates on this? We are evaluating striim and wal2json is a crucial part in this process. If you could shed a light, that would be very much appreciated .. tx!

**Comment by eulerto** [comment]
@OfficeUnlimited What is your OS? Are you using 64-bit while compiling wal2json? Dependency Walker shows that there is some missing Windows libraries. It seems there is some difference between your environment and the one used to build installer. I'm not in a Windows machine right now but one solution is to compile postgres and wal2json in the same environment.

**Comment by Venryx** [comment]
For people seeking the wal2json Windows binary (who don't want to compile from source), I found binaries provided here: https://www.striim.com/docs/smsgc/en/smsgc-how-to-guides/postgresql-to-google-cloud-postgresql-migration-guide/set-up-the-postgresql-source.html

After downloading, I just copied the dll file into the `C:\Program Files\PostgreSQL\VERSION\lib` folder, and restarted PostgreSQL.

(This does not answer the OP's question, however it may be relevant to people like me who came across this issue through Google searches, wanting to avoid installing the Visual C++ IDE, and going through the multiple build UI-based steps, just to get a binary of the lib. I would put it somewhere more appropriate, but this is the most-related issue I found.)
