### ISSUE TITLE
Is there a way to get the database name in the JSON?

### ISSUE THREAD

**Issue by drewdle** [eulerto/wal2json#155]
We have a setup involving one cluster with many nearly-identical databases. I am hoping to use wal2json to subscribe to this cluster and write to a multi-tenant database. Is it possible to include the database name in the json file?
Thanks!

**Comment by eulerto** [comment]
Yes, it is. However, I don't have a strong opinion about this request. Could you explain usefulness of this hypothetical new option? Application that establishes a connection know database name. Shouldn't you add it to your JSON file name?

**Comment by drewdle** [comment]
I was misunderstanding the capabilities of how the replication slot is
used, I believe. With barman it is cluster-wide. And that's what we need,
as we have many databases on our cluster that we need to track and we would
be above the limit of replication slots soon if we have to add one for each
database. I don't know what other plugins or tools to look at, and I would
be grateful for any suggestions.

Thank you again.

**Comment by eulerto** [comment]
@drewdle I don't know your scenario; I'm guessing but look at your architecture. Maybe using schemas instead of databases is a better approach. In this case, you have just one slot for all of your "databases". Having a lot of databases in the same cluster is not always a good idea. You should consider spreading your databases into multiple servers if you are running out of resources.

**Comment by drewdle** [comment]
Sorry it's taken me a while to get back to you, and thank you for your
response.

My situation is that I have inherited a system built up over the last 20
years that involved creating a new database for each new account. We have
over 600 databases. I know this is not a good idea or setup, but it is what
we have at the moment.

We are working toward creating a new system which will be multi-tenant,
having all of our accounts living nicely in one database. This is also
coinciding with having the data be consumed by other new apps we're
developing. Unfortunately, we can't set a cut-over date and do this at one
time; we have to keep version 1 going while we work on version 2, a data
warehouse, and other apps that are consuming this data in near real time.

So the thinking is that if we can get a stream of activity going on in
version 1, we can parse this downstream and apply some ETL magic before
loading it into something of a data lake or clearinghouse.

I hope I've made the situation I'm facing clearer.

Happy Friday, and thanks again.
Andy

**Comment by eulerto** [comment]
> My situation is that I have inherited a system built up over the last 20
years that involved creating a new database for each new account. We have
over 600 databases. I know this is not a good idea or setup, but it is what
we have at the moment.
>
600 databases in the same cluster? Per postgres architecture, you will have 600 replication slots, 600 wal senders which means 600 new processes just to handle logical replication. You can easily run out of resources depending on your workload.

I'm afraid you have to fix your app architecture before deploying CDC using wal2json.

**Comment by drewdle** [comment]
I will keep looking.
