### ISSUE TITLE
parse wal files to sql  

### ISSUE THREAD

**Issue by longtian001** [eulerto/wal2json#159]
When Secondary promoted we often need a tool parse wal files to get some sql( insert,update,delete) at WAL location RECPTR in HA Enviroment(Master-Secondary) ,sometimes sync some data of master from master wal files.

**Comment by eulerto** [comment]
I couldn't understand your goal. wal2json is just a plugin to output DML information into JSON objects. Do you want to have replication slot information into secondary server? This feature does not exist but was already proposed: [failover slots](https://www.postgresql.org/message-id/CANP8%2Bj%2Bqu7NV6QyaN4QgHo9kCD9fg0HhbwFFLpRuFA_6niXZ9g%40mail.gmail.com). If I don't answer your question, please explain your scenario.

**Comment by longtian001** [comment]
Sorry, may be I want another tool that only parse wal filse from special lsn to get DML SQL not by slots.
thanks

**Comment by longtian001** [comment]
when old master fail, secondary promoted to new master .sometimes old master still receive some SQL about bussiness,I only want a tool which gets these SQL statements started after forked LSN on old master's wal files .
you can close this, thanks.

**Comment by eulerto** [comment]
> may be I want another tool that only parse wal filse from special lsn to get DML SQL not by slots.

You can get DML data if you use logical decoding (slot is a key component). An old technique is capture data using triggers.

> when old master fail, secondary promoted to new master .sometimes old master still receive some SQL about bussiness,I only want a tool which gets these SQL statements started after forked LSN on old master's wal files .

This is possible using logical decoding. You can't advance logical replication slot when you promote new master. After that, you go to old master and execute `pg_logical_slot_peek_changes` to grab last transactions. How do you advance slot in normal operation? How do you merge data? (if you use serial datatype, you could possibly produce duplicate ids).

If you don't want to lose transactions why are you promoting without applying the backlog? There is no easy answer for the problem you described. Maybe you have to review it again and change some requirements.

wal2json is an output plugin that produces JSON objects, if you want an output plugin that produces SQL, you should try [decoder_raw](https://github.com/michaelpq/pg_plugins/tree/master/decoder_raw).

**Comment by longtian001** [comment]
I see what you mean,thanks
