### ISSUE TITLE
Column ordinal position

### ISSUE THREAD

**Issue by aandreakis** [eulerto/wal2json#160]
Looks like wal2json currently does not include the ordinal position of columns.
Is it possible to have an option for that ? 

This would enable to detect renamed columns. 

In Postgres, column positions can not be changed ([reference](https://wiki.postgresql.org/wiki/Alter_column_position)). The ordinal position stays the same for renamed column and new columns get a new ordinal position.

@eulerto

**Comment by eulerto** [comment]
Done in commit caaf9ac505519430c802d9ab1425e7c13007dc0c
