### ISSUE TITLE
Could not load library - Undefined symbol: TupleDescAttr

### ISSUE THREAD

**Issue by adautomeira** [eulerto/wal2json#162]
Using wal2json 2.2, I tried to do this:

`SELECT 'init' FROM pg_create_logical_replication_slot('json_replica', 'wal2json');`

But I got this:

ERROR:  could not load library "/opt/postgres/9.4.5/lib/postgresql/wal2json.so": /opt/postgres/9.4.5/lib/postgresql/wal2json.so: undefined symbol: TupleDescAttr

**Comment by eulerto** [comment]
@adautomeira What is your OS version? Why are you using such an old minor version? 9.4 is not supported anymore. If you want to stick with 9.4, upgrade to 9.4.26 as soon as possible.
[looking the code...]
It seems there is an oversight in format 2. I forgot to ifdef TupleDescAttr for old minor versions. I'll fix.

**Comment by eulerto** [comment]
Could you test the fix I applied a few minutes ago?

**Comment by adautomeira** [comment]
Sure!

**Comment by adautomeira** [comment]
It worked! Thanks a lot!
