### ISSUE TITLE
How to utilize publications with wal2json

### ISSUE THREAD

**Issue by flexzuu** [eulerto/wal2json#164]
Hey, i love the wal2json plugin.
We have a multi tenant db with a lot of schemas.
Sometimes we move tenants into the db with big transactions. 
We use the format version 1 because in normal operations we only send small transaction that we need to process as one message.

We would like to avoid processing of the big transactions.
How we planned to do this is utilizing publications.
We planed to create a publication and only and tenants tables to this publications after the initial big transactions because we are only interested in the changes after the big initial transactions.

I could not get wal2json work with publications. Do you have any info on how to utilize this together?

**Comment by eulerto** [comment]
Publications was introduced in version 10 and wal2json is a little older than that (introduced in 9.4). Although `wal2json` doesn't use publications, you can use parameters `add-tables` and `filter-tables` to select specific tables in your database. You can also use parameter `actions` to select SQL commands you want to process. In summary, you can emulate a publication with those 3 parameters.

By the way, publication support (for version 10+) seems to be a nice feature.

**Comment by flexzuu** [comment]
@eulerto thanks for the quick answer. We worked around our issue by using the new format and filtering on our side so we can close this if you like.

> By the way, publication support (for version 10+) seems to be a nice feature.
I agree it would be a nice feature. Especially because you can change what to filter for or at runtime. This would be a nice advantage over filter tables etc. As you can alter what tables a publication works on.
