### ISSUE TITLE
ENCODING OF WAL2JSON

### ISSUE THREAD

**Issue by congfairy** [eulerto/wal2json#165]
HI
     What charset does wal2json use to get the data from wal log? when my database server use sql-ascii, what charset will wal2json use to get the data?I am so curious about that .
Thanks

**Comment by eulerto** [comment]
Since wal2json uses **textual** output (_OUTPUT_PLUGIN_TEXTUAL_OUTPUT_), it produces data in server encoding. Indeed this is defined by the [logical decoding API](https://www.postgresql.org/docs/current/logicaldecoding-output-plugin.html#LOGICALDECODING-OUTPUT-MODE).
Do **not** use _SQL_ASCII_ unless you are only using ASCII characters. It does not validate and/or convert non-ascii characters.

**Comment by congfairy** [comment]
so if I use libpq to get wal log by"  "START_REPLICATION SLOT \"%s\" LOGICAL %X/%X (\"format-version\" '1',\"include-xids\" 'true'," 
            "\"include-timestamp\" 'true', \"pretty-print\" 'true', \"include-lsn\""
            "'true',\"include-not-null\" 'true', \"add-tables\" '%s')", 
            _replication_slot_name.c_str(), (uint32) (startpos >> 32), 
            (uint32) startpos, _replication_table.c_str());"
when I would like to get the bytea datatype, I get the utf8 hex data(server encoding is utf8),for example ,when I use insert into bytea values('a'),  and I get the data 61 which is utf8 hex encoding of a, So if I would like to get the data a, should I set the encoding to the connection?

**Comment by eulerto** [comment]
I forgot to add that logical decoding API produces data in server encoding but this data might or might not be converted depending on your client encoding. If you don't set `client_encoding` on your connection, current operating system locale will be used. `show client_encoding` displays what it got. Review libpq [connection string parameters](https://www.postgresql.org/docs/12/libpq-connect.html#LIBPQ-CONNSTRING) and [environment variables](https://www.postgresql.org/docs/12/libpq-envars.html) that explain about this topic. I also recommend you to take a look at the [character set](https://www.postgresql.org/docs/12/multibyte.html) documentation.
