### ISSUE TITLE
issue with clang

### ISSUE THREAD

**Issue by hugojdb** [eulerto/wal2json#166]
Hi,

when running USE_PGXS=1 make, i have the following error:

wal2json % USE_PGXS=1 make
/opt/local/bin/clang-mp-6.0 -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I. -I./ -I/usr/include -I/Library/PostgreSQL/12/include/postgresql/server -I/Library/PostgreSQL/12/include/postgresql/internal -I/opt/local/Current/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk  -I/opt/local/include/libxml2  -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include -flto=thin -emit-llvm -c -o wal2json.bc wal2json.c
make: /opt/local/bin/clang-mp-6.0: No such file or directory
make: *** [wal2json.bc] Error 1

my clang:

clang -v
Apple clang version 11.0.3 (clang-1103.0.32.59)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

my gcc:

gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.59)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Any idea how to fix the install?

thanks,
hugo

**Comment by eulerto** [comment]
`make CC=clang`

**Comment by hugojdb** [comment]
thanks, but it is still giving the exact same error.

**Comment by eulerto** [comment]
Could you share the `pg_config` output? Could you post the `make` output? `make` should change the compiler to `clang` but per your description it does not change. How did you install Postgres?

**Comment by hugojdb** [comment]
sure, pg_config:

 pg_config
BINDIR = /Library/PostgreSQL/12/bin
DOCDIR = /Library/PostgreSQL/12/doc/postgresql
HTMLDIR = /Library/PostgreSQL/12/doc/postgresql
INCLUDEDIR = /Library/PostgreSQL/12/include
PKGINCLUDEDIR = /Library/PostgreSQL/12/include/postgresql
INCLUDEDIR-SERVER = /Library/PostgreSQL/12/include/postgresql/server
LIBDIR = /Library/PostgreSQL/12/lib
PKGLIBDIR = /Library/PostgreSQL/12/lib/postgresql
LOCALEDIR = /Library/PostgreSQL/12/share/locale
MANDIR = /Library/PostgreSQL/12/share/man
SHAREDIR = /Library/PostgreSQL/12/share/postgresql
SYSCONFDIR = /Library/PostgreSQL/12/etc/postgresql
PGXS = /Library/PostgreSQL/12/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-llvm' '--with-icu' '--enable-debug' '--host=x86_64-apple-darwin' '--prefix=/mnt/hgfs/pginstaller_12.auto/server/staging_cache/osx.build' '--with-ldap' '--with-openssl' '--with-perl' '--with-python' '--with-tcl' '--with-bonjour' '--with-pam' '--enable-thread-safety' '--with-libxml' '--with-uuid=e2fs' '--with-includes=/opt/local/Current/include/libxml2:/opt/local/Current/include:/opt/local/Current/include/security' '--docdir=/mnt/hgfs/pginstaller_12.auto/server/staging_cache/osx.build/doc/postgresql' '--with-libxslt' '--with-libedit-preferred' '--with-gssapi' 'host_alias=x86_64-apple-darwin' 'CFLAGS=-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.9 -arch x86_64 -O2' 'LDFLAGS=-L/opt/local/Current/lib -L/opt/local/libexec/llvm-6.0/lib' 'LLVM_CONFIG=/opt/local/bin/llvm-config-mp-6.0' 'CLANG=/opt/local/bin/clang-mp-6.0' 'ICU_CFLAGS=-I/opt/local/Current/include' 'ICU_LIBS=-L/opt/local/Current/lib -licuuc -licudata -licui18n' 'PERL=/Library/edb/languagepack/v1/Perl-5.26/bin/perl' 'PYTHON=/Library/edb/languagepack/v1/Python-3.7/bin/python3'
CC = gcc
CPPFLAGS = -I/opt/local/Current/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -I/opt/local/include/libxml2 -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.9 -arch x86_64 -O2
CFLAGS_SL = 
LDFLAGS = -L/opt/local/Current/lib -L/opt/local/libexec/llvm-6.0/lib -L/opt/local/libexec/llvm-6.0/lib -L/opt/local/lib -Wl,-dead_strip_dylibs
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -ledit -lm 
VERSION = PostgreSQL 12.3

and make CC=clang:

make CC=clang
/opt/local/bin/clang-mp-6.0 -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I. -I./ -I/usr/include -I/usr/local/opt/llvm/include -I/Library/PostgreSQL/12/include/postgresql/server -I/Library/PostgreSQL/12/include/postgresql/internal -I/opt/local/Current/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk  -I/opt/local/include/libxml2  -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include -flto=thin -emit-llvm -c -o wal2json.bc wal2json.c
make: /opt/local/bin/clang-mp-6.0: No such file or directory
make: *** [wal2json.bc] Error 1

Appreciate the help,
thanks

**Comment by eulerto** [comment]
There is something wrong with your compiler setup. `pg_config` says that your Postgres was compiled with `gcc` and it will use it to build extensions. However, it seems to be using CLANG variable. Could you try forcing `gcc`?

`make CC=gcc`

**Comment by hugojdb** [comment]
i tried, and tried other workaround, but always end up having /opt/local/bin/clang-mp-6.0
