### ISSUE TITLE
SSL enabled connection issue for PostgreSQL and wal2json

### ISSUE THREAD

**Issue by PHXHoward** [eulerto/wal2json#170]
Hello, we have had success using wal2json with PostgreSQL 10.6 database.  We have recently forced SSL. With SSL forced, our streaming user can connect successfully but it does not receive any data.  Is There any additional configuration needed for wal2json to work with SSL connections? 

Thanks,
Howard

**Comment by eulerto** [comment]
The short answer is **no**. Are there related ERROR messages in the postgres logs? Since you didn't provide details or a use case, I cannot help you.

**Comment by PHXHoward** [comment]
Thanks for the reply. We have a case open with Streamsets to troubleshoot
the issue. Your reply that there is no inherent issue with TLS and the
wal2json plugin at least let's me know that there is a solution. All I can
say is that the handshake between the client and server is successful and
the streaming user logs in but no data comes across when TLS is enabled.
No errors in the PostgreSQL log so I'm not sure what else I can add. Hope
that the vendor has a solution.

Best,
Howard

**Comment by eulerto** [comment]
I advise you to update your minor version (10.6 -> 10.13). There are some fixes related to SSL.

**Comment by PHXHoward** [comment]
Hi. The newest version I see is wal2json 2.2 from February 14 on the github
page. Is that the newest version? I'm not sure how to tell which minor
version we are running but I believe we downloaded it more recently than
February 14.

**Comment by eulerto** [comment]
@PHXHoward I meant the Postgres version. The latest wal2json version is 2.2.
