### ISSUE TITLE
Using with bundled postgresql database

### ISSUE THREAD

**Issue by jjscarlett** [eulerto/wal2json#171]
I'm trying to compile this for use with a postgres v9.6 database that came bundled/preinstalled with another piece of software. Building it errors out because there aren't any *.h files present in the bundled postgres install. There are only a lib, bin, and share folders.
Suggestions?

**Comment by eulerto** [comment]
You didn't provide enough information. What is your OS? Read the instructions provided in the [README](https://github.com/eulerto/wal2json#unix-based-operating-systems).

**Comment by jjscarlett** [comment]
Oops sorry, win2016.
I think I figure it out. I installed the same version of PostgreSQL on another Win2016 server and then copied the missing files over to the server with PostgreSQL bundled and was then able to build the dll.
