### ISSUE TITLE
Out of order messages emitted (AWS Aurora PostgreSQL)

### ISSUE THREAD

**Issue by dko-slapdash** [eulerto/wal2json#172]
I see a strange output of the plugin (screenshot below). Basically, `{"change":[` follows another `{"change":[` immediately (without `]}` in between), and LSN order of these messages becomes scrambled too. I thought it was an artifact of the decoding plugin, but then I started dumping the raw data as it is, and the wrong order is there too. So it's definitely what Aurora returns.

My question: is it a bug in Aurora, or it's by design in wal2json?

(May also be correlated to large transactions.)

![image](https://user-images.githubusercontent.com/46383452/88454737-69f58a80-ce26-11ea-96bd-26d4198b0aee.png)

```
START_REPLICATION SLOT abc LOGICAL 0/0 ("include-types" '0', "write-in-chunks" '1', "add-tables" '.....')
```

**Comment by dko-slapdash** [comment]
Also, here is some small repro (not in AWS, just in a local PostgreSQL v12.2) for the case of reordering (it doesn't explain how could it be that multiple `{"change":[` follow each other without the `]}` between them, but anyway).

On the below example, we can see that the records emitted by the plugin DO NOT have always-ascending monotonic LSN. Sometimes a new transaction's beginning (`{"change":[` block) may have a LSN which is strictly LOWER than LSN of the previous record. How is that possible at all? Doesn't the plugin read the records always in the order of appearance in the replication log (and LSN is the offset in this log), so shouldn't LSN be always ascending/monotonic?

```
$ createdb pgtest
$ pgbench -i pgtest
$ psql pgtest
> ALTER TABLE pgbench_history ADD id bigserial NOT NULL PRIMARY KEY;
> SELECT pg_create_logical_replication_slot('pgtest_00', 'wal2json');
^D
$ pgbench pgtest -c 30 -t 20
$ psql pgtest
> SELECT * FROM pg_logical_slot_peek_changes('pgtest_00', null, null, 'include-types', '0', 'write-in-chunks', '1', 'include-lsn', '1'); 
```

![image](https://user-images.githubusercontent.com/46383452/88474931-0c257900-cee0-11ea-937d-67c4286418db.png)

**Comment by eulerto** [comment]
I cannot comment on wal2json plugin on Aurora because I don't know if AWS modifies it. You should ask AWS.

The "change" followed by another "change" can happen when you are using `write-in-chunks` because wal2json are not emitting all transaction at once. It means that if you disconnect in the middle of the transaction, a reconnection will emit that transaction from the beginning. I advise you to use format 2 (it should be the default format in a future version). 

You are misunderstanding the way WAL works (read #52 and commit dc6e390ef43c737cdfc8895f4b33babd0d8e1bb4. Use `nextlsn` if you need a reference for your application).

If you already have your test around, execute:

`pg_waldump $PGDATA/pg_wal/000000010000000400000081`

search for txn 36842147 and inspect around it.

**Comment by dko-slapdash** [comment]
I carefully read the links you provided, and they added some clarity to my understanding for sure. However, I think your previous comment answers slightly different questions (related though) and not quite the ones which were raised; I totally understand that, because you answered that different questions many times in various github issues.

In particular, 

1/ "`{"change":[` follows another `{"change":[` immediately (without `]}` in between)": here - https://www.postgresql.org/docs/11/logicaldecoding-output-plugin.html - I found the following: "Concurrent transactions are decoded in commit order, and only changes belonging to a specific transaction are decoded between the begin and commit callbacks" - this hints that it guarantees that there must be nothing between `{"change":[` and `]}` but the actual committed rows, because wal2json directly injects `{"change":[` in the begin callback and `]}` in the commit callback. And this is what I see in most of the cases (at least I can't repro the otherwise situation except of the very 1st screenshot from Aurora which doesn't repro anymore as well). You mention "The "change" followed by another "change" can happen" - but **how do I reproduce this**? In all my artificial tests, it never happens. Are you sure that they can happen? The screenshot below illustrates that PG actually never emits begin-begin without the intermediate commit:

<img width="1440" alt="Screen Shot 2020-07-27 at 12 11 32 AM" src="https://user-images.githubusercontent.com/46383452/88513877-f8404c80-cf9d-11ea-8c52-c4951ec5fb78.png">

2/ I also wonder, how does PG make (1) without internal buffering, knowing that LSNs are not always emitted in a monotonic way (like on the screenshot ago). Imagine the 1st transaction was huge, and it decoded it entirely (see (1)). But then it found out that there is a `commit` record of the 2nd transaction, so what does PG do then? does it rewind the xlog file back finding the beginning of that 2nd transaction (to guarantee that there is nothing between begin and commit emitted)? If not, how can we explain that LSNs in pg_logical_slot_peek_changes output jump backwards?

**Comment by eulerto** [comment]
> You mention "The "change" followed by another "change" can happen" - but how do I reproduce this? In all my artificial tests, it never happens. Are you sure that they can happen?

I said "if you disconnect in the middle of the transaction, a reconnection will emit that transaction from the beginning". Which means if you disconnect **after** the `begin_cb` output is sent and **before** the `change_cb` output is sent, you can reproduce the issue. If you need to use `write-in-chunks` consider using format 2, it is easier to control the stream of changes (mainly because every message is a JSON object).

> PG make (1) without internal buffering, knowing that LSNs are not always emitted in a monotonic way (like on the screenshot ago). Imagine the 1st transaction was huge, and it decoded it entirely (see (1)). But then it found out that there is a commit record of the 2nd transaction, so what does PG do then? does it rewind the xlog file back finding the beginning of that 2nd transaction (to guarantee that there is nothing between begin and commit emitted)? If not, how can we explain that LSNs in pg_logical_slot_peek_changes output jump backwards?

Logical decoding has a module called `reorder buffer` (cf `src/backend/replication/logical/reorderbuffer.c`).

```
 *    This module gets handed individual pieces of transactions in the order
 *    they are written to the WAL and is responsible to reassemble them into
 *    toplevel transaction sized pieces. When a transaction is completely
 *    reassembled - signaled by reading the transaction commit record - it
 *    will then call the output plugin (cf. ReorderBufferCommit()) with the
 *    individual changes. The output plugins rely on snapshots built by
 *    snapbuild.c which hands them to us.
```

**Comment by dko-slapdash** [comment]
Thanks.

OK, so "if you disconnect in the middle of the transaction, a reconnection will emit that transaction from the beginning" means that **if there is no disconnect**, then there should be no `{"change":[` follows another `{"change":[` immediately (without `]}` in between) even in theory, correct? (I need this as a proof to AWS support guys, to confirm that it's definitely a bug on their end.)

Another reason I'm asking about "begin after begin with no commit in between" is because I need to figure out the simplest way to write a decoder code. If the protocol guarantees that there are nothing in between begin and commit within the same connection, then I may always assign the changes to LSN=nextlsn of the previous `begin` message, and I don't need to have a temporary map of xid=>nextlsn.

P.S.
You mentioned earlier (and in other issues) about format 2; the thing is that it's not supported in AWS, it's heavier in terms of traffic, and also I read in some issue here that you wrote: "format 2 does not provide nextlsn. Ooops. That's a design flaw and I will implement it later". Anyway, it's just a different format of the same underlying concepts. (Having invalid JSONs doesn't hurt much in practice.)

**Comment by eulerto** [comment]
**wal2json** does not emit "change followed by change". I cannot comment on a closed source product that does not even mention the wal2json version it is using.

AWS advertised that it is using [wal2json 2.1](https://aws.amazon.com/about-aws/whats-new/2020/03/amazon-rds-now-supports-postgresql-12/) which supports format 2. As for "format 2 design flaw" you should check the last commits.

**Comment by dko-slapdash** [comment]
For those who finds this thread in the future, leaving the comment from our codebase:
```
// PG and wal2json don't guarantee that the individual messages are strictly
// ordered by their LSNs. The only guarantees we have are:
// 1. the "transaction commit" messages' LSNs are strictly ordered;
// 2. between "transaction begin" and "transaction commit" messages, there
//    are only messages related to this particular transaction.
//
// To achieve the above guarantees, PG uses "reorder buffer" abstraction
// which accumulates up to 4096 (hardcoded even in PG v12!) messages in
// memory, and the rest is "spilled" to disk, then read when needed. (Thus
// BTW, huge transactions are slow: PG writes them to the "spill files". See
// https://blog.anayrat.info/en/2018/03/10/logical-replication-internals/
// for details.)
//
// So to be short, we can't advance the slot with LSNs of individual
// messages. We can only advance with transaction commit LSNs as soon as
// they happen. (Otherwise we'd be losing messages after restarting in the
// middle of a large transaction.)
//
// To achieve this, we DON'T yield the message as soon as we read it from
// the replication stream. Instead, we store it in the following 1-slot
// backlog and yield it only when:
// 1. a new message arrives (aka "1 message backlog"); in this case, we
//    never advance the LSN;
// 2. a "transaction commit" message arrives; in this case, we advance the
//    slot with the commit message LSN when the message itself is acked by
//    the caller.
let prevMessage: Message | null = null;
...
// The emitted values will be pieces of JSON from wal2json (see
// "write-in-chunks" option) in one of the four following formats:
// - {"change":[
// - {"kind":"...", ...}
// - ,{"kind":"...", ...}
// - ]}
//
// If pg_logical_emit_message(true, 'touch', '{schema,table,id}') is
// called from a trigger, it will be delivered here too, e.g.:
// - {"kind":"message", "prefix":"touch",
//   "content":"{'schema':'...','table':'...','id':'...'}"}
```
