### ISSUE TITLE
For readme: wal2json is the only output plugin which fully supports pg_logical_emit_message()

### ISSUE THREAD

**Issue by dko-slapdash** [eulerto/wal2json#173]
Just checked pglogical and pgoutput plugins source code and noticed that none of them supports message_cb actually. So it's maybe worth mentioning in wal2json's readme that it's the only solution (since pg_logical_emit_message() is a very important tool in non-trivial streaming usecases, to e.g. signal about changes in dependent one-to-many tables etc.).

https://github.com/postgres/postgres/blob/9de77b5453130242654ff0b30a551c9c862ed661/src/backend/replication/pgoutput/pgoutput.c#L111-L117

https://github.com/2ndQuadrant/pglogical/blob/19d6f4f93b0985bb167f00953689f0ed489647fb/pglogical_output_plugin.c#L97-L104

**Comment by eulerto** [comment]
commits 37d3bfba40956b4199ded32ffff57cf21aa9297a and a93c9db89e833b7a68ffe690e28e22f43e7ec45b fix it.
