### ISSUE TITLE
Wrong value for txid which should not be displayed as an int

### ISSUE THREAD

**Issue by quentinbricard** [eulerto/wal2json#174]
I am using the latest version of wal2json plugin.
My postgres version is 12.2

When using include-xids, I noticed resulting value is wrong when `txid_current()` is more than 2*max_int = `4,294,967,294`
When printing xid value, `%u` is used, which is suited for unsigned decimal (integer) number
See: https://github.com/eulerto/wal2json/blob/master/wal2json.c#L805

Here is how to reproduce:

    select txid_current();
    // if returning value is less than 4294967294
    do $$
    declare
    n bigint;
    begin
        
        for n in SELECT * FROM generate_series(1, 4294967294) as a(n)
            loop
            perform txid_current();
            commit;
    end loop;
    end $$;
   // could take a while

Once it's finished, in another terminal: do a simple test:

    pg_recvlogical -d postgres --slot test_slot --start -o include-xids=true -o add-tables=public.table_test -o  pretty-print=1 -f -

In another terminal:

    begin;CREATE TABLE public.table_test (a text); INSERT INTO public.table_test(a) VALUES('test');select txid_current();commit;
    BEGIN
    CREATE TABLE
    INSERT 0 1
     txid_current 
    --------------
     4294967297
    (1 row)
    COMMIT

Result:

    {
	"xid": 1,
	"change": [
		{
			"kind": "insert",
			"schema": "public",
			"table": "table_test",
			"columnnames": ["a"],
			"columntypes": ["text"],
			"columnvalues": ["test"]
		}
	]
   }

Note from https://www.postgresql.org/docs/current/functions-info.html:

Name | Return Type | Description
-- | -- | --
txid_current() | bigint | get current transaction ID, assigning a new one if the current transaction does not have one

**Comment by svv2014** [comment]
According to this 
https://stackoverflow.com/questions/38561/what-is-the-argument-for-printf-that-formats-a-long

Looks like it should be using `%lu` or `%ld` but at the same time some people say that it is still `32 bit` and better to use `%lld` which is stands for  `64 bit`

**Comment by eulerto** [comment]
Code is correct. Internal representation of transaction id is 32 bits (TransactionId) [1]. `txid_current` returns FullTransactionId [3][4] but output plugin API uses only TransactionId [2].

[1] https://www.postgresql.org/docs/current/routine-vacuuming.html#VACUUM-FOR-WRAPAROUND
[2] https://github.com/postgres/postgres/blob/master/src/include/c.h#L520
[3] https://wiki.postgresql.org/wiki/FullTransactionId
[4] https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=2fc7af5e966043a412e8e69c135fae55a2db6d4f

**Comment by quentinbricard** [comment]
Alright, thank you
I just assumed the returned value to be wrong if more than this thresdhole
