### ISSUE TITLE
Emit signal within shutdown callback

### ISSUE THREAD

**Issue by anishbose** [eulerto/wal2json#176]
Currently have wal2json running as a plugin in a Postgres replication slot where a Debezium connector digests the data.

When I restart Postgres, Debezium holds onto the connection, which causes Postgres to wait for 10min before force-killing the connection.

This [issue](https://issues.redhat.com/browse/DBZ-1839) from a Debezium forum discusses the problem, and it was suggested that maybe there is a way within shutdown_cb to signal to Debezium that the connection needs to be terminated.

Would recommend reading through the thread for more detail, but would it be possible to emit a signal during shutdown_cb to alert the client (Debezium) about the connection needing to be killed?

**Comment by eulerto** [comment]
Postgres (walsender) certainly closes the replication connection accordingly. It means that the other peer (app) receives a FIN packet from Postgres (even if you send a SIGQUIT).

```
    postgres.9912 > app.42604: Flags [F.], cksum 0x73b6 (incorrect -> 0xf034), seq 1768, ack 624, win 509, options [nop,nop,TS val 2317327271 ecr 863763], length 0
 00:00:00.000684 IP (tos 0x0, ttl 64, id 9916, offset 0, flags [DF], proto TCP (6), length 52)
```

and the other peer (app) has to handle the connection close accordingly. If it is not, you cannot blame Postgres. If there is a bug, it is client-side.

AFAICS this has nothing to do with the output plugin API. Connection close is handled by walsender (cf `src/backend/replication/walsender.c` - `WalSndSignals`). Why would `shutdown_cb` duplicate the `(quick)die` feature?

**Comment by anishbose** [comment]
I see, thank you for the quick response! Looks like there's a bit of confusion from the Debezium side, so I'll follow up with them. 

Feel free to close the issue and I'll reopen if something new arises.

**Comment by anishbose** [comment]
@eulerto I was told by some Debezium developers that "Debezium does not handle network communication level at all - this is delegated to Postgres JDBC driver."

Does the wal2json plugin interact at all the the JDBC driver?

**Comment by eulerto** [comment]
@anishbose there is no interaction from Debezium to wal2json directly. The interaction is between Debezium and Postgres (walsender). wal2json is just a library that is loaded by walsender to produce the desired output format. [Logical Decoding documentation](https://www.postgresql.org/docs/12/logicaldecoding.html) explains about this infrastructure.

Better ask the Debezium developers why it does not handle the FIN packet sent from Postgres after a SIGQUIT.
