### ISSUE TITLE
How to allow inserts and deletes only using wal2json plugin

### ISSUE THREAD

**Issue by vhpriya16** [eulerto/wal2json#177]
We would like to block updates and allow only inserts and deletes for the replication to replicate those records. How can we achieve that ?

**Comment by eulerto** [comment]
parameter `actions`.

**Comment by vhpriya16** [comment]
syntax please ?

**Comment by mvalletta** [comment]
try
SELECT data FROM pg_logical_slot_peek_changes('rep_slot', NULL, NULL, 'format-version=2', 'actions=insert,delete')

**Comment by vhpriya16** [comment]
it didn't work

psql -c "SELECT data FROM pg_logical_slot_peek_changes('rep_slot', NULL, NULL, 'format-version=2', 'actions=insert,delete');" widh
ERROR:  option "format-version=2" = "actions=insert,delete" is unknown
CONTEXT:  slot "na_to_eu_rep_slot", output plugin "wal2json", in the startup callback

same error for format-version=1

**Comment by manerohit388** [comment]
@vhpriya16 Which PostgreSQL version you are using ?

**Comment by eulerto** [comment]
@vhpriya16 you seem to be using version 1 or earlier. Check [releases](https://github.com/eulerto/wal2json/releases). `actions` and `format-version` were introduced in version 2.0. Use the latest version.
