### ISSUE TITLE
wal2Json decoding plugin using too much of Lambda memory.

### ISSUE THREAD

**Issue by manerohit388** [eulerto/wal2json#178]
We have implemented Logical Replication on AWS using Aurora PostgreSQL 10.11 Version and Lambda. Lambda is using psycopg2 python library and it is scheduled to run every 5 mins. It is configured to use 512 MB memory and 5 mins timeout.  It connects to the DB and calls cursor.start_replication() with below parameters. 
`cur.start_replication(slot_name=os.environ['slotName'], 
options={'pretty-print': Constants.INT_ONE, 'include-lsn': True, 'filter-tables': Constants.FILTER_TABLES }, 
decode=True)`

If there are no messages read from replication slot then lambda execution is stopped and it shows that it has consumed 77 MB memory which is quite understandable.
 
I am committing transaction which contains 7.5K records and total size of the payload is 40 MB. Lambda code is successfully reading the transaction and processing the records but when I see memory used for lambda, it shows 477 MB. My understanding is that my payload size is 40 MB so lambda shouldn't consume 477 MB memory. I doubt if wal2json decoding is taking too much memory to decode the data ? Anyone who has implemented Logical replication on AWS using Lambda has observed this behavior ?

**Comment by dko-slapdash** [comment]
I think you need to pass `write-in-chunks: 1` parameter. But be careful: I spent a lot of time recently trying to figure out, when and what LSNs should be used when advancing the slot in the database, and the current conclusion is - only use LSNs of the "transaction commit" message (which is `]}` for wal2json v1 in `write-in-chunks: 1` mode). Don't even try using other LSNs, you'll lose data on a restart in the middle of transaction.

See https://github.com/eulerto/wal2json/issues/172#issuecomment-691876869 and https://blog.anayrat.info/en/2018/03/10/logical-replication-internals/ for details.

**Comment by eulerto** [comment]
@manerohit388 I don't know how you obtain 477 MB but it is possible that the logical decoding of a single transaction can took a lot of memory/disk (`walsender`) when your 40 MB transaction is a long running transaction. In this case, a decoding process will decode all changes between the transaction start and transaction end (it could possibly spill those transactions to disk). My advice is to avoid long running transactions; split your big transaction into small pieces.
