### ISSUE TITLE
Unable to read data from replication slot when it stay a long period without any data manipulation

### ISSUE THREAD

**Issue by manerohit388** [eulerto/wal2json#179]
We have a replication slot to capture the changes from WAL file, process those changes using lambda and stream them into kinesis. Lambda function runs at specific time interval, it connects  to DB and starts reading changes from replication slot. Lambda is configured to run for 5 mins. In 5 mins it processes whatever data it can and then it flushes next_lsn of last processed replication message and stops. On next lambda run it starts reading changes from next_lsn onward. 

Reading changes  from slot using below code.

`cur.start_replication(slot_name=os.environ['slotName'],
                              options={'pretty-print': Constants.INT_ONE, 'include-lsn': True,
                              decode=True)

cur.read_message()`

We have observed that normally replication slot works as expected. If there are no DB operations performed like insert, update or delete then lambda doesn't provide any acknowledgment back to server.  If there are no DB activities performed then after few days replication slot becomes inactive. After that any changes to DB are captured by replication slot but lambda is not able to read any changes from slot even though slot has the changes until we perform get_changes() from DB tool or removes replication slot. This increases replication lag and disk usage increases.  

Thanks

**Comment by eulerto** [comment]
`read_message` returns `None` if there is nothing to consume in the replication slot. Inactive replication slot means there is no replication connections using it. What is the `pg_replication_slots` output? You can always use `pg_logical_slot_peek_changes` function to inspect your backlog.

**Comment by manerohit388** [comment]
@eulerto Thanks for your response. As soon as we execute start_replication() on slot, status changes from inactive to active and then it goes back to inactive state. Using `pg_logical_slot_peek_changes` I can see that there is data in the replication slot but when lambda tries to read data from replication slot it, `read_message` returns none. 

Let me know if you need any other information to understand the issue.

Thanks
