### ISSUE TITLE
Unidentified memory leak(?)

### ISSUE THREAD

**Issue by GarageDeveloper** [eulerto/wal2json#180]
Dear all,
we are using wal2json in combination with debezium and have been facing what we think to be a memory leak as all our walsender processes are eating more and more resident memory (several hundreds of megabytes per hour) and we need to restart DBZ several time per day to free up memory.
Environment:
Debian buster (10.x) with packages from apt.postgresql.org:
```
ii  postgresql-12                  12.2-2.pgdg100+1              amd64        object-relational SQL database, version 12 server
ii  postgresql-12-wal2json         2.2-1.pgdg100+1               amd64        PostgreSQL logical decoding JSON output plugin
ii  postgresql-client-12           12.2-2.pgdg100+1              amd64        front-end programs for PostgreSQL 12
ii  postgresql-client-common       213.pgdg100+1                 all          manager for multiple PostgreSQL client versions
ii  postgresql-common              213.pgdg100+1                 all          PostgreSQL database-cluster manager
```
It seems related to both wal2json and the activity of our DB and not to DBZ in itself as we were able to reproduce the problem with pg_recvlogical:
```
pg_recvlogical -d test_db -U test_u -p 5433 -W --slot test_slot --create-slot -P wal2json
pg_recvlogical -d test_db -U test_u -p 5433 -W --slot test_slot --start -f /dev/null
```
After about 10 minutes, the related walsender eats around 120Mbytes, then 200Mbytes and so on. Actually 375Mbytes after 20 minutes. Other debezium walsender processes which have been running for 5 hours are each eating 2.1Gbytes of RSS.
For now we have not been able to reproduce this on a simple test db with only a pgbench running in an infinite loop, that's why I guess this is related to something specific in our DB activity.
I'll keep you informed of our research but if you have any track you can give on the way to figure this out, that'd be great.
Thanks,
Raph

**Comment by eulerto** [comment]
@GarageDeveloper what wal2json version are you using? Are you using additional parameters? Which ones?

Could you attach the `gdb` to the walsender process?

```
$ gdb -p $walsender_pid
(gdb) p MemoryContextStats(TopMemoryContext)
```

it dumps the memory context statistics to postgresql log file (or stderr).

**Comment by GarageDeveloper** [comment]
@eulerto as mentioned in my initial post, the version used is wal2json 2.2 as packaged by the PostgreSQL team.
Please find the command (I had to add a cast to (long) and hope it is ok) used and its output:
```
(gdb) p (long)MemoryContextStats((long)TopMemoryContext)
```
The output is attached. [memory.txt](https://github.com/eulerto/wal2json/files/5292603/memory.txt)
As far as I can see, it may be related to ReorderBufferToastHash. Please let me know if you need any other actions on my side. We're still looking into it here.
Thx.

**Comment by GarageDeveloper** [comment]
@eulerto we've just did further testing with pgoutput plugin instead of wal2json and we get the exact same problem of memory usage growing indefinitely. I'm cloging this issue as I'm more and more convinced this is 100% PostgreSQL related. I guess this is related to logical decoding in general.
Thanks and keep up your marvelous work.
