### ISSUE TITLE
detecting version using sql

### ISSUE THREAD

**Issue by wesselvdv** [eulerto/wal2json#181]
Is there a way to detect which version of wal2json is installed using a sql statement?

**Comment by eulerto** [comment]
No, it is not. :(

The system view `pg_available_extensions` doesn't list wal2json because it doesn't have a control file. Since it doesn't need to install functions or other objects, I didn't provide the extension infrastructure.

Why kind of problem are you trying to solve?

**Comment by wesselvdv** [comment]
We're trying to support different versions of wal2json for [`@graphile/subscription-lds`](https://www.npmjs.com/package/@graphile/subscriptions-lds). This npm package is using logical replication in combination with wal2json to provide live graphql subscriptions on tables. We're interested in utilising multiple newer options that will require us to validate if it's possible to use them beforehand. (`version-format 2`, `include-pk`)

**Comment by igouss** [comment]
I think v1 format is here to stay because there are a few apps that depend on it.
However, eulerto should probably specify that v2 is the format to use for new apps. So you should specify that you support v2 only.
