### ISSUE TITLE
When i use Debezium and wal2json it cause a problem

### ISSUE THREAD

**Issue by chzhty001** [eulerto/wal2json#183]
The error info:
Caused by: org.postgresql.util.PSQLException: ERROR: out of memeory
  Detail: Cannot enlarge string bugger containing 1073741788 bytes by 217 more bytes.
  Where: slot "debezium", output plugin "wal2json", in the change callback, associated LSN xxxxxx

**Comment by eulerto** [comment]
You have a big transaction. `format version 1` allocates one string for the whole transaction. The maximum size for `format version 1` is **1 GB** (this is a PostgreSQL infrastructure limitation). You have 3 options:

* use smaller transactions and keep `format version 1`;
* use `format version 1` and enable `write-in-chunks`;
* user `format version 2`.

I recommend that you adopt format version 2. I will be the default in future versions.

**Comment by chzhty001** [comment]
> * `format version 2`.

how can i use format version 2? is it a config item?

**Comment by eulerto** [comment]
Parameter `format-version`. There is an example in the [README](https://github.com/eulerto/wal2json/blob/master/README.md#sql-functions).
