### ISSUE TITLE
RedShift support

### ISSUE THREAD

**Issue by Tagar** [eulerto/wal2json#184]
AWS RedShift is PostgreSQL under the hood 

Would this package support RedShift out of the box?

**Comment by eulerto** [comment]
Ask AWS.

**Comment by Tagar** [comment]
Created an AWS support case.. let's see how far I can go with that :-) 

Generally, does `pg_recvlogical` needs to run locally on postgresql server? If yes, I guess this would be a non-starter for RedShift integration. Thx

**Comment by eulerto** [comment]
`pg_recvlogical` is a client application. You can run it in another host.

**Comment by Tagar** [comment]
@eulerto I got a response from an AWS engineer that RedShift doesn't have a WAL, they only have some Postgres pieces on the frontend for ODBC/ JDBC connections etc. I had a lot of wishful thinking.. :-)
