### ISSUE TITLE
Digital Ocean Managed PostgreSQL Support

### ISSUE THREAD

**Issue by pepijnverburg** [eulerto/wal2json#185]
Hi all,

A little while back Digital Ocean supported the `wal2json` extension by default (for example https://ideas.digitalocean.com/ideas/DBAAS-I-24, see the comments). Tried to look for documentation why this support seems to be dropped. Does anyone have information about this? Version incompatibility? Feel free to close this issue if you think this is not the place to question this, but this might be good for visibility.

I did see a fairly recent request with DO to support the extension again, so if anyone wants to vote please do:
https://ideas.digitalocean.com/ideas/DBAAS-I-107

**Comment by eulerto** [comment]
Ask DigitalOcean.
