### ISSUE TITLE
plan for integrating DDL changes

### ISSUE THREAD

**Issue by mijoharas** [eulerto/wal2json#186]
Hi, referring to your comment here https://github.com/eulerto/wal2json/issues/115#issuecomment-490186368 I'd like to ask if there's a plan to integrate ddl transactions into wal2json?

If so, how would that work? my understanding is that ddl statements aren't supported by postgres's logical replication [ref](https://www.postgresql.org/docs/10/logical-replication-restrictions.html)

**Comment by eulerto** [comment]
When if said

> DDL (besides TRUNCATE that is already supported) should be incorporated in a few releases.

the _releases_ refer to **Postgres releases**. My preferred solution for this problem is to add support for DDLs into logical decoding.

**Comment by mijoharas** [comment]
Hahaha ofc! OK, that makes perfect sense. Thanks for the explanation. :+1:
