### ISSUE TITLE
empty changes reported on UPDATE statement

### ISSUE THREAD

**Issue by cemeyer2** [eulerto/wal2json#189]
I have a database where I have a simple table. INSERTs show up fine with CDC using wal2json, but UPDATE statements give me 

```
{
	"change": [
	]
}
```

This is leveraging aws aurora with postgres compatibility. 

I am likely missing something basic, so any advice is appreciated! Thanks!

**Comment by drdee** [comment]
Did you verify that `identity replica` (on that table)  is not set to `nothing` but at least set to `default` ?

**Comment by cemeyer2** [comment]
that was it, thanks @drdee
