### ISSUE TITLE
include_values

### ISSUE THREAD

**Issue by frafra** [eulerto/wal2json#190]
Hi!
I would like to propose a new option, which would be set to `true` by default, named `include_values`.
This option, when set to false, would not stream any values.

Would it be enough to wrap this line in a `if` and add a new option?
https://github.com/eulerto/wal2json/blob/f3650d71f972152c9c6a23a8d5ec84290bf3e4f1/wal2json.c#L1341

**Comment by eulerto** [comment]
What is the purpose of such an option?

**Comment by frafra** [comment]
The purpose is to send a notification without sending the actual data, which is useful for monitoring or fetching some selected data afterwards.

**Comment by eulerto** [comment]
If your client is using the SQL interface you can query `pg_stat_replication` and `pg_replication_slots` for monitoring. If you want to fetch data without consuming it, use `pg_logical_slot_peek_changes`.
