### ISSUE TITLE
Include comment schema, table and value

### ISSUE THREAD

**Issue by frafra** [eulerto/wal2json#191]
Here is the output when a comment is added:
```
{'action': 'B'}
{'action': 'C'}
```
It would be interesting to know something about the comment.

**Comment by eulerto** [comment]
Which comment? Provide a description of what you are trying to get/do.

**Comment by frafra** [comment]
When I comment on a table or on a schema, I do not see that in the stream. I just see a transaction starting and ending with nothing in between.

https://www.postgresql.org/docs/current/sql-comment.html

**Comment by eulerto** [comment]
logical replication does not replicate DDL yet.
