### ISSUE TITLE
Get user that made a change

### ISSUE THREAD

**Issue by dorijangrgic** [eulerto/wal2json#197]
Hi,

is it possible to add a new parameter that holds information about a user?

E.g., it could be called _include-user_.

**Comment by eulerto** [comment]
No. Postgres doesn't store information about which user has modified a row. If you want to capture this information you need to write a BEFORE trigger that stores the user information into a table column. See [this example](https://www.postgresql.org/docs/current/plpgsql-trigger.html#PLPGSQL-TRIGGER-EXAMPLE) in the Postgres documentation.

**Comment by dorijangrgic** [comment]
Thank you very much!
