### ISSUE TITLE
Cloud DBaaS providers with support for wal2json

### ISSUE THREAD

**Issue by Venryx** [eulerto/wal2json#199]
Does anyone have a list of which PostgreSQL DBaaS providers support this wal2json plugin?

It's a required plugin for Postgraphile's ["live query" functionality](https://www.graphile.org/postgraphile/live-queries), and I'd like to assess what database-provider options are available.

Of the major providers, it seems that only some support it:
* Amazon: **Yes** (listed in their [PostgreSQL service user guide](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.FeatureSupport.Extensions.12x))
* Google Cloud: **Yes** (listed as supported in the [logical-replication-page](https://cloud.google.com/sql/docs/postgres/replication/configure-logical-replication#introduction), despite not being listed in the [general extensions list](https://cloud.google.com/sql/docs/postgres/extensions#postgresql-extensions-supported-by-cloud-sql))
* Azure: **Probably** (listed in [this documentation](https://docs.microsoft.com/en-us/azure/postgresql/concepts-logical), though not in the extensions list of any of these three server-type extensions pages: [single-server](https://docs.microsoft.com/en-us/azure/postgresql/concepts-extensions), [flexible-server](https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-extensions), [hyperscale-citus](https://docs.microsoft.com/en-us/azure/postgresql/concepts-hyperscale-extensions))

Other providers:
* Digital Ocean: **Yes** (https://docs.digitalocean.com/products/databases/postgresql/resources/supported-extensions)
* Aiven: **Yes** (https://help.aiven.io/en/articles/489561-supported-postgresql-extensions)
* Heroku: No (https://devcenter.heroku.com/articles/heroku-postgres-extensions-postgis-full-text-search)

It'd be nice to find some additional providers that support it, as alternatives to avoid vendor lock-in.

(@eulerto Feel free to close this issue, as it's more of a knowledge repository than an active issue.)

**Comment by eulerto** [comment]
* Digital Ocean: yes (https://docs.digitalocean.com/products/databases/postgresql/resources/supported-extensions/)

**Comment by eulerto** [comment]
I didn't test Azure but [documentation](https://docs.microsoft.com/en-us/azure/postgresql/concepts-logical?WT.mc_id=devto-blog-abhishgu) claims it is supported.

**Comment by Venryx** [comment]
Thanks, added DigitalOcean to the list!

Also, interesting that Azure does claim to support wal2json; I don't know why it's not listed on any [of](https://docs.microsoft.com/en-us/azure/postgresql/concepts-extensions) [the](https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-extensions) [three](https://docs.microsoft.com/en-us/azure/postgresql/concepts-hyperscale-extensions) extensions pages. Anyway, I'll update the note.

As an alternative to fully-managed database providers, it's worth noting that there are a number of "virtual private server" providers that give full control of the (virtualized) system, which would allow someone to install PostegreSQL + whatever extensions they want. This is the route I'm currently planning to go. (partly for wal2json, but also because there are some other customizations I anticipate wanting to add)

The two that look best to me so far are these:
1) Kamatera (starting at $4/mo): https://www.kamatera.com/express/compute
2) A2 Hosting (starting at $5/mo): https://www.a2hosting.com/vps-hosting/unmanaged

What I like is that these VPS providers give you detailed control over storage space, memory capacity, cpu count, etc., with the cost increasing only for what you actually need. So it has the "pay for what you need" benefit of cloud providers, while offering full control (eg. to install PostgreSQL with custom plugins, and persistent storage). I will likely have to move up from those base settings/prices pretty soon, but it's nice to be able to do this gradually as the need arises (unlike many of the other VPS and dedicated-server providers).

Anyway, I will update the DBaaS and VPS provider lists above as I find more good ones.

**Comment by Venryx** [comment]
As an alternative to fully-managed database providers, it's worth noting that there are a number of "virtual private server" providers that give full control of the (virtualized) system, which would allow someone to install PostegreSQL + whatever extensions they want. This is the route I'm currently planning to go. (partly for wal2json, but also because there are some other customizations I anticipate wanting to add)

The two that look best to me so far are these:
1) Kamatera (starting at $4/mo): https://www.kamatera.com/express/compute
2) A2 Hosting (starting at $5/mo): https://www.a2hosting.com/vps-hosting/unmanaged

What I like is that these VPS providers give you detailed control over storage space, memory capacity, cpu count, etc., with the cost increasing only for what you actually need. So it has the "pay for what you need" benefit of cloud providers, while offering full control (eg. to install PostgreSQL with custom plugins, and persistent storage). I will likely have to move up from those base settings/prices pretty soon, but it's nice to be able to do this gradually as the need arises (unlike many of the other VPS and dedicated-server providers).

Anyway, I will update the DBaaS and VPS provider lists above as I find more good ones.

**Comment by eulerto** [comment]
* Aiven: yes (https://help.aiven.io/en/articles/489561-supported-postgresql-extensions)

**Comment by legopin** [comment]
Recently saw GCP update their offering
Announcement blog post
https://cloud.google.com/blog/products/databases/you-can-now-use-cdc-from-cloudsql-for-postgresql

Docs
https://cloud.google.com/sql/docs/postgres/replication/configure-logical-replication

**Comment by Venryx** [comment]
Interesting. It looks like Google Cloud's PostgreSQL service does support wal2json!

From: https://cloud.google.com/sql/docs/postgres/replication/configure-logical-replication
> For example, the wal2json extension allows streaming all changes in a database to a consumer, formatted as JSON. Cloud SQL supports the built-in pgoutput decoder, the test_decoding contrib module, and wal2json. These plugins enable replication to non-PostgreSQL databases.

It annoys me that the "extensions" page for that same service does not list it: https://cloud.google.com/sql/docs/postgres/extensions#postgresql-extensions-supported-by-cloud-sql

I guess they just neglected to update that second page.

**Comment by dc-pm** [comment]
On this topic; I've been trying to find out for some time but it appears that DO appears to be in denial about this topic, as they have no superuser access or logical replication support AFAICS - which is a real shame.

It's interesting as the documentation clearly states that this is supported and has for some time, but without the ability to enable logical replication this seems to be useless. Does anyone have other experience here?
