### ISSUE TITLE
Are transactions serialized in wal2json output?

### ISSUE THREAD

**Issue by ovandriyanov** [eulerto/wal2json#204]
May I expect that:
1) In format version 2 there will be no nested transactions, i.e. the following is impossible:
```json
{"action":"B"}
{"action":"I","schema":"public","table":"table1_with_pk","columns":[{"name":"a","type":"integer","value":1}
{"action":"B"}
{"action":"I","schema":"public","table":"table2_with_pk","columns":[{"name":"a","type":"integer","value":1}
{"action":"C"}
{"action":"I","schema":"public","table":"table3_with_pk","columns":[{"name":"a","type":"integer","value":1}
{"action":"C"}
```
2) In format version 1, when using `include-xids`, receiving a change with `xid` which differs from the `xid` of the previous change designates the commit of the previous transaction and the beginning of a new one?

**Comment by eulerto** [comment]
@ovandriyanov Logical decoding processes transactions one at a time. No, there won't be nested transactions while streaming the transactions. However, have in mind that non-transactional messages will be streamed before the transaction that contains it. See an example in the [README](https://github.com/eulerto/wal2json/blob/master/README.md).

**Comment by ovandriyanov** [comment]
Thank you very much!
