### ISSUE TITLE
Can I parser json to sql format?

### ISSUE THREAD

**Issue by leandrotocachelis** [eulerto/wal2json#211]
wal2json output in json format.
Can I parser from json to sql format?

Thanks.

**Comment by mvalletta** [comment]
Use decoder_raw plugin
(https://paquier.xyz/postgresql-2/postgres-9-4-feature-highlight-output-plugin-logical-replication/)
(https://github.com/michaelpq/pg_plugins/tree/master/decoder_raw)

**Comment by leandrotocachelis** [comment]
> Use decoder_raw plugin
> (https://paquier.xyz/postgresql-2/postgres-9-4-feature-highlight-output-plugin-logical-replication/)
> (https://github.com/michaelpq/pg_plugins/tree/master/decoder_raw)

I'm using AWS RDS and not possible using plugin decoder_raw

Because of that I need to create json and then convert to .sql

**Comment by eulerto** [comment]
Well, as the name suggests, it only provides JSON output.
