### ISSUE TITLE
Unable to start postgresql 14 after installing wal2json

### ISSUE THREAD

**Issue by durgackm** [eulerto/wal2json#213]
I installed wal2json on mac using command 'brew instal wal2json' which also installed postgres 14.0.
After that I added the below two statements in postgresql.conf file 
_shared_preload_libraries = 'wal2json'
wal_level = logical_ 

pg_ctl is throwing the following error
 % pg_ctl start                                
waiting for server to start....2021-10-08  FATAL:  incompatible library "/usr/local/lib/postgresql/wal2json.so": version mismatch
**2021-10-08 13:19:13.559 IST [20073] DETAIL:  Server is version 14, library is version 13.**
2021-10-08 13:19:13.560 IST [20073] LOG:  database system is shut down

**Comment by dhenson02** [comment]
@durgackm brew gave you a prebuilt binary that came from an older version.  uninstall that and build from latest source locally instead (on the server with PG)
