### ISSUE TITLE
No nextlsn included

### ISSUE THREAD

**Issue by coffenbacher** [eulerto/wal2json#214]
I'm not sure what's going on here, but the docs imply that a `nextlsn` value will be included if I run:

```sql
select data from pg_logical_slot_peek_changes(
      'test_slot', NULL, 100,
      'format-version', '2',
      'include-timestamp', 'on',
      'include-transaction', 'false',
      'include-lsn','true',
      'include-pk', 'true');
 ```
 
 I only see an `lsn` key. Any ideas what might be causing this?

**Comment by coffenbacher** [comment]
If I use format version 1, I do see `nextlsn` values.

**Comment by eulerto** [comment]
@coffenbacher you're probably using a wal2json 2.2 or a previous one. [version 2.3](https://github.com/eulerto/wal2json/releases/tag/wal2json_2_3) includes commit 8600d480de304ffe4c6a313b6fba1e411ab2e706 that fixed an oversight in format 2.
