### ISSUE TITLE
All columns aren't included in the log file. 

### ISSUE THREAD

**Issue by anmoncada** [eulerto/wal2json#223]
Hi, 

There are changes which all columns are not included in the log. For example: 

If a user did an update in the table with the following columns: id, value1, value2, value3. When we review pg_peek_changes only shows id, value1 and value2.

**Comment by eulerto** [comment]
UPDATE will not provide columns for new tuple whose values have not been modified and its value is stored in a TOAST table.

That's not a wal2json problem; that's how logical decoding provides data to output plugin. If you want to confirm it, set `log_min_messages = debug1`, try your UPDATE and you'll get:

```
column "foo" has an unchanged TOAST
```
