### ISSUE TITLE
the removal of 'x' in "\x" corrupts data

### ISSUE THREAD

**Issue by mydimension** [eulerto/wal2json#23]
I have data in a table the holds valid hex `\x` sequences (e.g. `"\x1b"` for an encoded [ESC] character). The following code in `quote_escape_json` seems to be the culprit:

```
/* XXX suppress \x in bytea field? */
if (ch == '\\' && *(valptr + 1) == 'x')
{
	valptr++;
	continue;
}
```

With this, my `"\x1b"` value is emitted from this plugin as `"\1b"`.

Even if this is right thing to do for bytea values (not convinced it is), it is not correct for other textual data.

**Comment by eulerto** [comment]
I've already detected this problem while working in another patch. I'll fix it.
