### ISSUE TITLE
Problem to 'make' on Rocky Linux

### ISSUE THREAD

**Issue by nurulasyikinhariyanto99** [eulerto/wal2json#235]
When I run the 'make' command, this is the output displayed. How can I solve these issues?

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o wal2json.o wal2json.c
Assembler messages:
Fatal error: can't create wal2json.o: Permission denied
make: *** [<builtin>: wal2json.o] Error 2

**Comment by eulerto** [comment]
It seems the wal2json directory are not owned by the current user (you probably clone the repository or extracted the source code with root). Hence, the compiler cannot create files into the current directory.
