### ISSUE TITLE
Updates or deletes returns empty changeset

### ISSUE THREAD

**Issue by jefflee91** [eulerto/wal2json#239]
I am getting empty chagesets whenever an update statement is executed in one of my test tables.

Python code:

source_conn = pg.connect("dbname='data-warehouse-test' host='hubblebase.cmgdthsodgpa.ap-southeast-1.rds.amazonaws.com' user='repluser_kinesis_poc' password='vJn32C46JKyp'", connection_factory = LogicalReplicationConnection)
cur = source_conn.cursor() 

cur.drop_replication_slot('wal2json_test_slot_2')
cur.create_replication_slot('wal2json_test_slot_2', output_plugin = 'wal2json')
cur.start_replication(slot_name = 'wal2json_test_slot_2', options = { 'pretty-print' : 0, 'include-timestamp': 1, 'add-tables': 'public.test_postgres_kinesis'}, decode= True)

def consume(msg):
print(msg.payload)

cur.consume_stream(consume)

Running an INSERT statement generates:
`{"timestamp":"2022-04-01 08:05:27.492533+00","change":[{"kind":"insert","schema":"public","table":"test_postgres_kinesis","columnnames":["id","project_id","job_id","created_at"],"columntypes":["uuid","character varying","character varying","timestamp without time zone"],"columnvalues":["6f855ccd-88dd-40fc-b786-f2e46204227c","33380213","2094623980","2022-02-16 08:06:21.446758"]}]}
`

However, running an UPDATE statement generates:
`{"timestamp":"2022-04-01 07:50:39.109693+00","change":[]}`

**Comment by eulerto** [comment]
Your table probably doesn't have a primary key or a replica identity.

**Comment by jefflee91** [comment]
Got it, I updated my test table to contain primary keys, and it's able to capture non-empty changesets. Thanks!
