### ISSUE TITLE
Excluding empty changesets from being logged/streamed

### ISSUE THREAD

**Issue by jefflee91** [eulerto/wal2json#240]
Is there a parameter setting that I can use to exclude empty changesets from being written to WAL (ie. {"timestamp":"2022-04-05 04:08:33.930348+00","change":[]})? If yes, how do I format it as part of the 'cur.start_replication' function

**Comment by eulerto** [comment]
It seems related to #239. No, there is no parameter to control it. Make sure you are using a primary key or replica identity in all published tables.
