### ISSUE TITLE
[Feature Request] Add a way to output parsed `jsonb` or `json` fields

### ISSUE THREAD

**Issue by BigsonLvrocha** [eulerto/wal2json#242]
Hello, thanks for the wonderful plugin

Is there a way for the value of jsonb or json fields not to be string, but the object itself?
It could be an option for the plugin, this way there would be no reason to parse `json` fields in the consumer service. 

Would be an option like `parse-json-fields` and default would be false, if true, value is the object itself, not the encoded string of the object

**Comment by eulerto** [comment]
I'm afraid I didn't understand your feature request. If you are talking about the [logical decoding SQL interface](https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-REPLICATION), the `pg_logical_slot_*_changes` functions returns the column `data` whose data type is `text`. You can cast this column to `jsonb` or even create another function that converts the output to `jsonb` so you don't need to cast the column `data` directly.

```
euler=# SELECT pg_typeof(data), pg_typeof(CAST(data AS jsonb)) FROM pg_logical_slot_peek_changes('test_slot', NULL, NULL, 'pretty-print', '1', 'add-msg-prefixes', 'wal2json');
WARNING:  table "table2_without_pk" without primary key or replica identity is nothing
 pg_typeof | pg_typeof 
-----------+-----------
 text      | jsonb
 text      | jsonb
(2 rows)
```

If that's not what you have in mind, try to explain.

**Comment by docteurklein** [comment]
sorry for the necrobump, but I think I have the same issue.

Here are reproducible steps:

```sql

select * from pg_create_logical_replication_slot('s1', 'wal2json');

create table t1 (d jsonb primary key);

insert into t1 values(to_jsonb(text ''));

select data::jsonb from pg_logical_slot_peek_changes(
            's1',
            null,
            null,
            'pretty-print', '0',
            'include-default', '0',
            'format-version', '2',
            'include-types', '0',
            'include-transaction', '0'
        )
```

outputs:

```
 {"table": "t1", "action": "I", "schema": "pim", "columns": [{"name": "d", "type": "jsonb", "value": "\"\""}]}
```

while I could have expected:

```
 {"table": "t1", "action": "I", "schema": "pim", "columns": [{"name": "d", "type": "jsonb", "value": ""}]}
```

Hope it makes sense.
