### ISSUE TITLE
bytea data not properly decoded

### ISSUE THREAD

**Issue by rugging24** [eulerto/wal2json#25]
Hello,
I recently found out that bytea columns are not properly decoded. The bytea data comes in some
strange decoding that is not in any way similar to the source data.

Could this be some kind of bug ?

cheers .

rugging24

**Comment by eulerto** [comment]
Seems the same as #23. I'll work on a fix.

**Comment by rugging24** [comment]
I found a workaround to this by not decoding the streams obtained with wal2json.

If it helps, am using the streaming protocol from psycopg2 and essentially set the decode flag False.
