### ISSUE TITLE
wal2json limitation 

### ISSUE THREAD

**Issue by Ajaydbaaws** [eulerto/wal2json#254]
Hi Team,
We want to stream the data from Aurora PostgreSQL db (version 12.8) using Striim(CDC tool) which use replication slot for streaming purpose.

Replication slot is created using below command.

SELECT pg_create_logical_replication_slot('striim_rt_<dbname>', 'wal2json');

Striim(CDC) tool is failing  to process the data from Aurora PostgreSQL db when DB transaction size is more than 1 GB. 

wal2json version - wal2json for Aurora Postgres 12.8 is 2.3.

I wanted to check if there are any limitation around wal2json? is there any fix for this issues. pls help and provide direction which can help overcome this problem.

Regards
Ajay

**Comment by eulerto** [comment]
Regarding the 1 GB limit, you have 3 options; (a) break your transaction into small pieces, (b) use `write-in-chunks` option with format 1 or (c) use format 2.

Regarding Aurora, you should ask Amazon. I don't know if they use the code as-is or it is a modified version.
