### ISSUE TITLE
Can't enable truncation for format-version 1

### ISSUE THREAD

**Issue by cjbottaro** [eulerto/wal2json#256]
I'm using format-version 1 and the actions param...
```
START_REPLICATION SLOT change_stream_postgres_cdc_consumer_format1 LOGICAL 0/20C54A0 ("include-timestamp" 'true', "include-xids" 'true', "format-version" '1', "actions" 'insert,update,delete,truncate')
```

But when I truncate a table, this is the JSON that comes across:
```
{"xid":3372,"timestamp":"2022-11-16 22:09:19.19005+00","change":[]}
```

How can I enable logging of truncate commands when using format-version 1?

Thanks for the help.

**Comment by eulerto** [comment]
@cjbottaro TRUNCATE is not supported by format version 1. See commit b93fb620. However, it you really need it, adjust the function [pg_decode_truncate_v1](https://github.com/eulerto/wal2json/blob/master/wal2json.c#L2661).
