### ISSUE TITLE
WAL2JSON Format-1 not including Current lsn

### ISSUE THREAD

**Issue by Sarath33** [eulerto/wal2json#257]
May i know the reason why the current lsn value is not placed in the format-1 log. It will be very helpful while using wal2json format-1 with write-in-chunks option to trace the begin position of the transaction.

`{"xid":2809,"nextlsn":"9/2E9C8210","timestamp":"2022-11-1400:28:05.500002-08","change”:[{“kind":"insert","schema":"public","table":"srctable22","columnnames":["nn"],"columntypes":["bytea"],"columnoptionals:”[true],"columnvalues:”[“6f70706c6c"]}]}`

**Comment by shubhamdhama** [comment]
@Sarath33 what version of `wal2json` are you using?

**Comment by Sarath33** [comment]
@shubhamdhama i am using wal2json 2.1 version. Also let me know in any of the new version does current lsn is also gets included in the json string.

**Comment by eulerto** [comment]
> May i know the reason why the current lsn value is not placed in the format-1 log.

... because it maintains backward compatibility.
