### ISSUE TITLE
When attempting logical decoding : /usr/lib64/pgsql/wal2json.so: undefined symbol: elog_finish

### ISSUE THREAD

**Issue by PatrickS136** [eulerto/wal2json#258]
I am currently trying to use the plugin on Postgres 13 on Almalinux 8 WSL, but I continuously encounter this error on elog_finish

My packages:
Package postgresql-server-devel-13.7-2.module_el8.6.0+2906+ee60d910.x86_64 is already installed.
Package postgresql-server-13.7-2.module_el8.6.0+2906+ee60d910.x86_64 is already installed.
Package postgresql-13.7-2.module_el8.6.0+2906+ee60d910.x86_64 is already installed.
pg_config --version : PostgreSQL 13.5

$ pg_recvlogical -d postgres --slot test_slot --create-slot -P wal2json -h /tmp
pg_recvlogical: error: could not send replication command "CREATE_REPLICATION_SLOT "test_slot" LOGICAL "wal2json" NOEXPORT_SNAPSHOT": ERROR:  could not load library "/usr/lib64/pgsql/wal2json.so": /usr/lib64/pgsql/wal2json.so: undefined symbol: elog_finish

**Comment by eulerto** [comment]
It seems your installation is broken. Package name reports 13.7 but `pg_config` reports 13.5. _shrug_

Reinstall all your PostgreSQL packages (including wal2json).

**Comment by PatrickS136** [comment]
Got it thanks 🙏
