### ISSUE TITLE
Events are resent

### ISSUE THREAD

**Issue by yasontr** [eulerto/wal2json#26]
Hi,

I noticed a scenario in which events are resent. This can be found here: https://www.postgresql.org/message-id/CANcxKGKg5eof4Zm1fj-8EhirX9ZT4gnZyNoVEXqp74wruJvg8A%40mail.gmail.com

I suspect that this is related to the wal2json plugin.

Please let me know when you need more information or testing from my side.

Thanks you.

**Comment by eulerto** [comment]
@yasontr what is your postgres version? Could you show pg_replication_slots output (column confirmed_flush_lsn is only available in 9.6) before and after insert?

**Comment by sanjioh** [comment]
Hi, and thank you for this project!

I'm experiencing this issue too (PostgreSQL 9.4.17).

I'm using Python 3.6.5, with PostgreSQL client library psycopg2 2.7.4.
I'm using this script to fetch events and print them on stanard output.

``` python
import sys

import psycopg2
import psycopg2.extras

conn = psycopg2.connect(
    host='127.0.0.1',
    port=5432,
    dbname='postgres',
    user='postgres',
    password='postgres',
    connection_factory=psycopg2.extras.LogicalReplicationConnection,
)
cur = conn.cursor()
try:
    # test_decoding produces textual output
    cur.start_replication(slot_name='pytest', decode=True)
except psycopg2.ProgrammingError:
    cur.create_replication_slot('pytest', output_plugin='wal2json')
    cur.start_replication(slot_name='pytest', decode=True)


class DemoConsumer(object):
    def __call__(self, msg):
        print(msg.payload)
        msg.cursor.send_feedback(flush_lsn=msg.data_start)


democonsumer = DemoConsumer()

print("Starting streaming, press Control-C to end...", file=sys.stderr)
try:
    cur.consume_stream(democonsumer)
except KeyboardInterrupt:
    cur.close()
    conn.close()
    print("The slot 'pytest' still exists. Drop it with "
          "SELECT pg_drop_replication_slot('pytest'); if no longer needed.",
          file=sys.stderr)
    print("WARNING: Transaction logs will accumulate in pg_xlog "
          "until the slot is dropped.", file=sys.stderr)
```


If I make an INSERT into a table, I get the following:
```
{"change":[{"kind":"insert","schema":"public","table":"newtable","columnnames":["id"],"columntypes":["integer"],"columnvalues":[6]}]}
```

If I kill the script and run it again, I get the same event, which souldn't happen due to the ```msg.cursor.send_feedback(flush_lsn=msg.data_start)``` call.
If I execute multiple INSERTs, only the last one is duplicated once the script runs the second time (the previous events seem to be acknowledged correctly).

Please let me know if I can help you with any test!

**Comment by sanjioh** [comment]
Oh, one last thing: if I use the ```test_decoding``` plugin I don't get the duplication behaviour.

**Comment by eulerto** [comment]
@sanjioh The plugin knows nothing about the replication restart point. The interface (in this case, psycopg2) is responsible for informing which LSN the plugin should start replication again. I advise you to open an issue at [psycopg2](https://github.com/psycopg/psycopg2).

If you repeat this test using `SQL API` or `pg_recvlogical` you will check that it will not resend data. Have a look at README to see the instructions.

**Comment by sanjioh** [comment]
Oh, ok then! Thank you very much for the answer :)
