### ISSUE TITLE
ERROR: could not load library "C:/Program Files/PostgreSQL/9.5/lib/wal2json.dll": The specified module could not be found.

### ISSUE THREAD

**Issue by tito0o0** [eulerto/wal2json#262]
hello, i already build file wal2json.dll, then put it at postgresql directory following tutorial steps, there is no error.
but after that i uninstall ms visual studio because i build wal2json.dll on RDP and make RDP disk full. 

then when i use following command in dbeaver :
SELECT * FROM pg_create_logical_replication_slot('warehouse', 'wal2json') ;

i have an error :
ERROR: could not load library "C:/Program Files/PostgreSQL/9.5/lib/wal2json.dll": The specified module could not be found.

i already check wal2json.dll file with same directory as error, and the file is still there. what should i do?

**Comment by Nickclc** [comment]
wal2josn.dll need windows c++ base code， you can install Visual Studio2012,only choice microsoft c++ module
