### ISSUE TITLE
NaN values are received as "null" for NUMERIC type while capturing change data 

### ISSUE THREAD

**Issue by SriSK97** [eulerto/wal2json#265]
`Table Definition : public.test (id int, col1 numeric(38), col2 numeric(22,7))`

With the above mentioned table, when a **NaN** value is inserted into the numeric columns, the raw transaction received sends **NULL** instead of **NaN**.  Although the table contents show the value is stored as **NaN**

```
postgres=# insert into public.test values (1, 'NaN', 'NaN');
INSERT 0 1
postgres=# select * from public.test;
 id   |  col1  | col2
------+--------+------
  1   |  NaN   |  NaN
(1 row)
```

Raw Transaction received : 
`{"xid":823,"nextlsn":"0/18495D8","timestamp":"2023-02-08 04:13:56.63704-08","change":[{"kind":"insert","schema":"public","table":"test","columnnames":["id","col1","col2"],"columntypes":["integer","numeric(38,0)","numeric(22,7)"],"columnoptionals":[true,true,true],"columnvalues":[1,null,null]}]}`

Questions : 
1. Is there any specific reason behind receiving NULL instead of NaN here?
2. Is there any way I can receive NaN itself instead of NULL?

**Comment by eulerto** [comment]
Yes. JSON spec does not allow strings as numbers. See issue #245 . PR #255 implemented it (commit bb7cd50). This feature should be in the next wal2json version.

**Comment by DimCitus** [comment]
Hi @eulerto ; do you have a schedule for the next release of wal2json? It would be nice if pgcopydb could always use the new option `numeric-data-types-as-string` and avoid replay errors as in the attached bug report. We can't at the moment without telling our users to deploy a locally built wal2json version, which is not ideal.

**Comment by eulerto** [comment]
@DimCitus I'm planning to create the release after PGCon. I'm still want to include a replication progress patch to this next release too. Expect a new release until the end of this month.

**Comment by eulerto** [comment]
It took a while but the new release is out.
