### ISSUE TITLE
Invalid JSON with non-transactional message

### ISSUE THREAD

**Issue by DemianD** [eulerto/wal2json#266]
We are currently receiving the following invalid JSON from the wal2json plugin:

```json
{"change":[,{"kind":"message","transactional":false,"prefix":"heartbeat","content":"2023-02-16 10:40:03.280759+00"}]}
```

There is an extra `,` in front of the array.
Every 30 seconds, we execute the following query that sends a heartbeat message:

```sql
SELECT pg_logical_emit_message(false, 'heartbeat', now()::varchar);
```

As you can see in the JSON above, `transactional` is set to `false`.
We've found the following code in the plugin, which should make sure that there is no extra `,` in front of the array.

https://github.com/eulerto/wal2json/blob/bb7cd505629e6fbd0846ff5cda787c0c486563c5/wal2json.c#L2516-L2530

We only have this error when there are a lot of transactions/large transactions (many inserts) in progress. This makes me suspect that the variable `nr_changes ` is being set incorrectly, or is not completely isolated.

**Comment by DemianD** [comment]
Ping @eulerto (sorry for pinging you directly). We would like to solve this, but don't know where to start. Do you happen to have an idea what the problem could be?

**Comment by eulerto** [comment]
What's your Postgres version? What's your wal2json version? Could you provide a reproducible test case?

**Comment by DemianD** [comment]
Thank you for your response, @eulerto.

We are currently using the following versions locally:

- Postgres version: `PostgreSQL 14.5 (Debian 14.5-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit`

- wal2json version: `Package: postgresql-14-wal2json - Version: 2.5-1.pgdg110+1` (installed using apt)

I've created a small video recording. At the bottom, you can find the SQL statements for the reproducible test case.

https://user-images.githubusercontent.com/5346497/219384869-2e9c27fd-b3a8-4e93-a848-e6a60c8d980b.mov

---

**File 1**:

```sql
-- Setup

SET search_path to "public";
DROP TABLE IF EXISTS "public"."outbox_messages";
CREATE SEQUENCE IF NOT EXISTS outbox_messages_id_seq;
CREATE TABLE "public"."outbox_messages" (
    "id" int4 NOT NULL DEFAULT nextval('outbox_messages_id_seq'::regclass),
    "payload" text NOT NULL,
    PRIMARY KEY ("id")
);

-- Start

SELECT 'init' FROM pg_create_logical_replication_slot('test_1', 'wal2json');
SELECT pg_logical_emit_message(false, 'heartbeat', now()::varchar);

-- While the other transaction is busy, execute the following statement a couple times:
SELECT pg_logical_emit_message(false, 'heartbeat', now()::varchar);

SELECT data FROM pg_logical_slot_peek_changes('test_1', null, null);
SELECT 'stop' FROM pg_drop_replication_slot('test_1');
```

**File 2**:
```sql
SET search_path to "public";

BEGIN;
INSERT INTO outbox_messages (payload) VALUES ('test1');
SELECT pg_sleep(3);
INSERT INTO outbox_messages (payload) VALUES ('test1');
SELECT pg_sleep(2);
INSERT INTO outbox_messages (payload) VALUES ('test1');
COMMIT;
```

**Comment by eulerto** [comment]
Thanks for your test case. This fix will be included in the next version.

**Comment by djairhogeuens** [comment]
@eulerto any idea on when the next version will be released?
