### ISSUE TITLE
WAL record received in different formats when the table name contains the single quote

### ISSUE THREAD

**Issue by MohamedKamarudeen** [eulerto/wal2json#267]
Configured the slot option with the `add-tables` parameter and the values specified the table names by comma separated. Received record is in different format when the specified table name contains a single quote character in the `add-tables` parameter.

Tables present in Postgresql DB as **public.emp'loyee**, **public.student**.

Configured the slot options `add-tables` as **public.student**.
WAL record received as 
```
{
	"action":"I",
	"xid":836,
	"timestamp":"2023-03-16 01:49:10.691667-07",
	"lsn":"0/1A0D7B8",
	"schema":"public",
	"table":"student",
	"columns":
				[
					{"name":"id",
					 "type":"integer",
					 "value":2,
					 "optional":true
					},
					{"name":"name",
					"type":"character varying(20)",
					"value":"name",
					"optional":true
					}
				]
}
```

Configured the slot options `add-tables` as **public.emp\\'loyee**  (table name contains single quote character) and also tried without the escape character(**public.emp'loyee**).
**WAL record received as in different format** 
```
{
	"xid":839,
	"nextlsn":"0/1A22DA8",
	"timestamp":"2023-03-16 01:57:03.901389-07",
	"change":
				[
					{
						"kind":"insert",
						"schema":"public",
						"table":"public.emp'loyee",
						"columnnames":["id","name"],
						"columntypes":["integer","character varying(20)"],
						"columnvalues":[2,"name"]
					}
				]
}
```

**Comment by eulerto** [comment]
In order to include a single quote character, [Postgres](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-CONSTANTS) requires you to add 2 single quote characters. Hence, the input (`add-tables` option) cannot be equal to the output format.
