### ISSUE TITLE
Change data not captured

### ISSUE THREAD

**Issue by ericvergnaud** [eulerto/wal2json#275]
Hi,

thanks for this very useful add-on.
Unfortunately, following the readme tutorial, I'm not able to get it working in docker.

I'm running a PostgreSQL 12.6 docker image, enhanced from the official docker image.
My docker file is as follows:
```
FROM postgres:12.16

RUN apt-get update
RUN apt-get install -y postgresql-12-wal2json
```

I run the above image using the following docker-compose.yml:
```
version: '3'

services:
  postgres:
    build: .
    image: pgsql-cdc/latest
    container_name: pgsql-cdc
    platform: linux/amd64
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=1"
      - "-c"
      - "shared_preload_libraries=wal2json"
```
(note the `shared_preload_libraries`, missing from the readme)

I open a docker terminal on the newly created pgsql-cdc container, and type the following:
```
su postgres
pg_recvlogical -d postgres --slot test_slot --create-slot -P wal2json
```

In the docker container logs I see:
```
2024-01-04 18:08:02 2024-01-04 17:08:02.476 UTC [156] LOG:  logical decoding found consistent point at 0/168D750
2024-01-04 18:08:02 2024-01-04 17:08:02.476 UTC [156] DETAIL:  There are no running transactions.
2024-01-04 18:08:02 2024-01-04 17:08:02.476 UTC [156] STATEMENT:  CREATE_REPLICATION_SLOT "test_slot" LOGICAL "wal2json" NOEXPORT_SNAPSHOT
```

I then run:
```
pg_recvlogical -d postgres --slot test_slot --start -o pretty-print=1 -f -

```

In the docker container logs, I see:
```
2024-01-04 18:09:12 2024-01-04 17:09:12.225 UTC [160] LOG:  starting logical decoding for slot "test_slot"
2024-01-04 18:09:12 2024-01-04 17:09:12.225 UTC [160] DETAIL:  Streaming transactions committing after 0/168D788, reading WAL from 0/168D750.
2024-01-04 18:09:12 2024-01-04 17:09:12.225 UTC [160] STATEMENT:  START_REPLICATION SLOT "test_slot" LOGICAL 0/0 ("pretty-print" '1')
2024-01-04 18:09:12 2024-01-04 17:09:12.225 UTC [160] LOG:  logical decoding found consistent point at 0/168D750
2024-01-04 18:09:12 2024-01-04 17:09:12.225 UTC [160] DETAIL:  There are no running transactions.
2024-01-04 18:09:12 2024-01-04 17:09:12.225 UTC [160] STATEMENT:  START_REPLICATION SLOT "test_slot" LOGICAL 0/0 ("pretty-print" '1')
```

So far, everything seems to work fine.

I then open PSequel (a desktop PostgreSQL client) and run:
```
CREATE TABLE stuff(a serial, b varchar(30), PRIMARY key(a));
INSERT INTO stuff(b) values('Hello!');
```
(note that PSequel uses auto commit)

In the docker container terminal, I'm not seeing any output.
Starting `pg_recvlogical` _after_ creating the table does not improve.

I then open a docker container terminal and run:
```
psql test_db
INSERT INTO stuff(b) values('Hello!')
COMMIT
```
In the docker container terminal, I'm still not seeing any output.

I've found that the only SQL statement that triggers a wal2json output is `CREATE DATABASE xxx` ...

What am I doing wrong ?

**Comment by ericvergnaud** [comment]
Worth noting, when I use SQL instructions:
```
SELECT 'init' FROM pg_create_logical_replication_slot('test_slot2', 'wal2json');
.../... (do some data changes)
SELECT data FROM pg_logical_slot_get_changes('test_slot2', NULL, NULL, 'format-version', '2');
SELECT 'stop' FROM pg_drop_replication_slot('test_slot2');
```
I get the expected output.

**Comment by ericvergnaud** [comment]
Turns out the issue originates from the readme, these lines:

```
$ pg_recvlogical -d postgres --slot test_slot --create-slot -P wal2json
$ pg_recvlogical -d postgres --slot test_slot --start -o pretty-print=1 -f -

```
only receive changes to the db named 'postgres'.
They should read:

```
$ pg_recvlogical -d table1_with_pk --slot test_slot --create-slot -P wal2json
etc...

```

(at least that's how I got the expected output with postgres 12)

I'll happily submit a PR if the above finding is correct.

btw, improved clarity would be welcome re `max_wal_senders` and `max_replication_slots`. Should they be set to 1 or 10 ?

**Comment by eulerto** [comment]
wal2json doesn't require to be loaded by `shared_preload_libraries` parameter. Logical replication is per database. You need to make sure to use the correct database name in the `pg_recvlogical` command line.
Read the documentation about `max_wal_senders` and `max_replication_slots`. BTW, I only added the `max_wal_senders` instruction because old versions ( < 10 ) defaults to zero. wal2json supports 9.4+.
