### ISSUE TITLE
Building dll for windows

### ISSUE THREAD

**Issue by onrdmr** [eulerto/wal2json#277]
I have this issue i changed path to 'C:\Program Files\PostgreSQL\15' like instruction said:

**Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		The BaseOutputPath/OutputPath property is not set for project 'wal2json.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform.	wal2json	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	832**

**Comment by onrdmr** [comment]
it works well but i need to install windows 10 sdk and retarget to project to my installed sdk otherwise it gives another error.
i have created this pull request https://github.com/eulerto/wal2json/pull/279 for this issue

**Comment by eulerto** [comment]
Hmm. Doesn't it work if you just set `WindowsTargetPlatformVersion` to your current SDK? Maybe if you remove `WindowsTargetPlatformVersion` line, it picks the SDK that is available. You can also use a [workaround](https://stackoverflow.com/questions/54134339/how-do-i-specify-any-windows-sdk-version-greater-than-10-0-in-a-visual-studio). I should probably mention that: (a) the current vcxproj file uses Visual Studio 2022 and Windows 10 and (b) you should adjust it based on your build environment and operating system version.

**Comment by onrdmr** [comment]
As you have said, we don't need WindowsTargetPlatformVersion in our .vsxproj file. It is come from retarget projects on project menu as you see here [visual studio 2022 ui](https://prnt.sc/Jmzxu6JOrbz0)
i have updated this pull request , https://github.com/eulerto/wal2json/pull/279 , from your feedback,
