### ISSUE TITLE
wal2json_16 is not available in CentOS7

### ISSUE THREAD

**Issue by apduvuri** [eulerto/wal2json#280]
Hi,
While trying to install latest wal2json in CentOS7, I am getting the error "No package wal2json_16 available". Please find the attached screenshot.

![image](https://github.com/eulerto/wal2json/assets/107536488/7e4372c8-6c25-4455-92a5-d9578e2a4881)

**Comment by eulerto** [comment]
wal2json project doesn't provide packages. The following URL indicates that no Postgres 16 packages will be available for RHEL-like distributions as of August 2023.

https://yum.postgresql.org/news/rhel7-postgresql-rpms-end-of-life/

See `yum repolist`. There is no `pgdg16/7/x86_64`.
