### ISSUE TITLE
Create an official release or tag

### ISSUE THREAD

**Issue by gunnarmorling** [eulerto/wal2json#29]
Hi, the [Debezium project](debezium.io) is interested in using this plug-in; would it be possible to cut an official release and/or tag so we have a stable version we can refer to? I'm a bit reluctant to pull in just the HEAD of master as it's a moving target inherently. So we currently refer a specific commit id, but having a named tag would be better of course. Thanks a lot for considering this request!

**Comment by eulerto** [comment]
@gunnarmorling I'll do after I confirm that some bugs were fixed and some features (generic WAL messages) are stable enough.

**Comment by rcoup** [comment]
@eulerto which tickets are you referring to in particular? (if I can lend a hand)

**Comment by eulerto** [comment]
@rcoup all of the opened issues. I've already have some patches for #30 and #35. I have to investigate #23 and have to work on #34.

**Comment by eulerto** [comment]
Stable release is out.

**Comment by OndraZizka** [comment]
Hi Euler, please where is the released `.so` file? I have compiled it for PG 10, but I need for 9.5 and I can't install it in my distribution anymore. I've tried compiling in `postgres` Docker container but didn't get that to work, and fiddling with the build from within the container is a bit hard. Is there some repo with the compiled files? Thanks.

**Comment by OndraZizka** [comment]
I have tried to compile in Docker container of `postgres:9.5`, but with the same result as with build against 10.4:
> ERROR: could not load library "/usr/local/lib/postgresql/wal2json.so": Error relocating /usr/local/lib/postgresql/wal2json.so: __snprintf_chk: symbol not found
