### ISSUE TITLE
Warning with update on table without primary key and data are lost

### ISSUE THREAD

**Issue by drrzmr** [eulerto/wal2json#30]
Hi!

Executing tests from README.md I take this case:
```
root@moses-dev.ceqw0lelg9w0.us-east-1.rds.amazonaws.com:moses_dev_db> SELECT data FROM pg_logical_slot_get_changes('test_slot', NULL, NULL, 'pretty-print', '1', 'write-in-chunks', '0');
WARNING:  table "table_without_pk" without primary key or replica identity is nothing

+--------+
| data   |
|--------|
| {
        "change": [
        ]
}        |
+--------+
SELECT 1
Time: 0.095s
```

But using *test_decoding* within another slot:
```
root@moses-dev.ceqw0lelg9w0.us-east-1.rds.amazonaws.com:moses_dev_db> SELECT data FROM pg_logical_slot_get_changes('test_slot2', NULL, NULL);
+-------------------------------------------------------------------------------------+
| data                                                                                |
|-------------------------------------------------------------------------------------|
| BEGIN 1890                                                                          |
| table public.table_without_pk: UPDATE: a[integer]:1 b[numeric]:2.34 c[text]:'anta2' |
| COMMIT 1890                                                                         |
+-------------------------------------------------------------------------------------+
SELECT 3
Time: 0.084s
```

Looking the source code I see another possibly points where WARNINGs will be printed and data discated, how I can bypass this and don't lose data? For my case use *test_decoding* and implement data parser is better option?

Thanks a lot!

**Comment by eulerto** [comment]
@drrzmr How do you expect to apply UPDATE or DELETE without a row identifier (primary key or replica identity)?
Why do you think wal2json should print such a change?

**Comment by drrzmr** [comment]
@eulerto In my case, I just don't want lose nothing that happens on database, my suggestion for this case are something like this:
```json
{
	"kind": "update",
	"schema": "public",
	"table": "table_without_pk",
	"columnnames": ["a", "b", "c"],
	"columntypes": ["integer", "numeric(5,2)", "text"],
	"columnvalues": [1, 2.34, "Anta"]
}
```
Just don't create "oldkeys" field, then the consumer knows that something happens, however couldn't know where. If you like this suggestion I can send a PR that implements this approach.
Other suggestion are output always be a json object, to errors and warnings too, I guess that way will make consumers happpier.

**Comment by cbandy** [comment]
:+1: for `"kind": "update"` lacking `"oldkeys"`.

**Comment by eulerto** [comment]
@drrzmr your case is a mere of configuration than a new wal2json option. If you have tables without primary key use REPLICA IDENTITY.

**Comment by drrzmr** [comment]
My suggestion are not about new wal2json option, it is about wal2json improvement. But never mind, thanks for your answer.
