### ISSUE TITLE
Expose scale and precision for NUMERIC columns

### ISSUE THREAD

**Issue by gunnarmorling** [eulerto/wal2json#31]
Hi, for columns such as `NUMERIC(10,3)`, we'll only see `NUMERIC` as a column type in corresponding messages, i.e. precision and scale are gone. It'd be great to have them, though, in order to derive corresponding schemas on the consumer side.

I'm not sure whether this (easily) can be done in wal2json, so I'm opening this to get a discussion started. For sure it'd be something were we'd benefit very much from in Debezium.

**Comment by eulerto** [comment]
@gunnarmorling it is possible. I'll take a stab later.

**Comment by jpechane** [comment]
As I am thinking about it it might be usefult to add it to other types that supoports custom length like varchar, time/date types etc.

**Comment by eulerto** [comment]
@gunnarmorling @jpechane I'll appreciate if you could test this new feature.

**Comment by jpechane** [comment]
Looks great, thanks @eulerto.
