### ISSUE TITLE
Tests fail _sometimes_

### ISSUE THREAD

**Issue by afiskon** [eulerto/wal2json#34]
Hi,

I noticed that various tests sometimes fail. I didn't explore the issue deeply but it looks like just a flaw of the tests, not a bug in the extension itself.

Example 1:
http://afiskon.ru/s/fc/53ae61ede5_regression.diffs.txt
http://afiskon.ru/s/d4/bd9a065311_regression.out.txt

Example 2:
http://afiskon.ru/s/79/11a4ea2430_regression.diffs.txt
http://afiskon.ru/s/35/1523b25c8b_regression.out.txt

The environment is Arch Linux x64, GCC 7.2.0, Core i7 3632QM 2200 Mhz (4 cores, 8 with HT).

**Comment by eulerto** [comment]
@afiskon Is it version 10?

**Comment by afiskon** [comment]
Yes, it's 10.

**Comment by eulerto** [comment]
@afiskon I couldn't reproduce it. Could you check again? I pushed some PR and did some enhancements.

**Comment by afiskon** [comment]
@eulerto This particular issue doesn't reproduce anymore. However now the `message` test always fails like this:

https://afiskon.ru/s/8b/155998a5fb_regression.diffs.txt
https://afiskon.ru/s/7a/c09baf7e51_regression.out.txt

Reproduces on both PostgreSQL 10 and 11.

**Comment by afiskon** [comment]
Here is how exactly I build and run PostgreSQL:

https://afiskon.ru/s/47/d46b9b783e_quick-build.sh.txt
https://afiskon.ru/s/fa/e2b93ea9c4_single-install.sh.txt

**Comment by eulerto** [comment]
@afiskon What is your server encoding?Could you check regression tests under locale C or any UTF-8 (if it is not the case)?

**Comment by afiskon** [comment]
Hello,

I'm using locale en_US.UTF-8. I execute regression tests for the master branch (i.e. 11) a few times a day, they are fine.

The environment is Arch Linux x64 if that matters, pretty much default configuration with i3wm.

**Comment by rich617** [comment]
These regression tests still fail intermittently on Windows with the same type of diff where there are one or more empty list entries extra from the test run. This is over two years in. Does anyone know where these extra entries are coming from? Can we modify the tests to filter out the empty entries from the test output?
