### ISSUE TITLE
Invalid JSON is generated for quoted identifiers

### ISSUE THREAD

**Issue by jpechane** [eulerto/wal2json#35]
When a qutoed identifiers are used - like when a table name contains space - then the JSON generator is not escaping the quotes and as a result the JSON is invalid.

**Comment by rcoup** [comment]
To reproduce:
```
CREATE TABLE "foo""' bar" (
    id integer NOT NULL,
    "more ""'quoting" integer
);
INSERT INTO "foo""' bar" VALUES (1,2);
```
Produces (pg_recvlogical):
```
{
	"change": [
		{
			"kind": "insert",
			"schema": "public",
			"table": "foo"' bar",
			"columnnames": ["id", "more "'quoting"],
			"columntypes": ["integer", "integer"],
			"columnvalues": [1, 2]
		}
	]
}
```
AFAICT it should be `"table": "foo\"' bar",` and `, "more \"'quoting"],`
