### ISSUE TITLE
Compile issue using USE_PGXS=1 make && make install

### ISSUE THREAD

**Issue by kushaank** [eulerto/wal2json#36]
Hi, I've been trying to use wal2son with kafka connect. However, I am not able to compile because the directory/file containing pgxs.mk cannot be found

I'm using Ubuntu 10.04 and postgres is installed under /usr/lib but it doesn't have the .mk file

I also tried installing postgresql from the source still didn't work. Any help would be greatly appreciated :)

**Comment by eulerto** [comment]
@kushaank You don't mention which postgres version. Did you install postgresql-server-dev-9.x? This package contains pgxs.mk.

**Comment by kushaank** [comment]
I'm using 9.6 and yes I downloaded that however the last line in the make file doesn't point to the right path for some reason. 
My postgres folder is usually in /usr/lib

**Comment by eulerto** [comment]
Could you show the output?

**Comment by kushaank** [comment]
Nvm that fixed it. I wasn't installing it before and didn't realize that. Maybe that could be a good addition to the Readme. Otherwise, it works thank you :)
