### ISSUE TITLE
Provide an option to output type OIDs instead of type names

### ISSUE THREAD

**Issue by lionel-panhaleux** [eulerto/wal2json#37]
Some connectors, namely Python [psycopg2](http://initd.org/psycopg/) in my case, use type OIDs directly for internal type conversion methods. In these cases it is far simpler to provide these OIDs directly and not rely on the type names.

Since a JSON output is a better API than the text-based example provided by Postgres, we should accommodate softwares using already existing connectors and frameworks. I hope this feature can be useful for a lot of people out there.

I'm providing a pull request for this feature, and am at your disposal for corrections  or improvements.

**Comment by eulerto** [comment]
@lionel-panhaleux I've added support for type oids. I'll appreciate if you could test this feature.

**Comment by lionel-panhaleux** [comment]
Tested on my end, works as a charm ! Indeed it's cleaner this way and options should not depend on one another. Thanks for the feature !
