### ISSUE TITLE
Provide an optional flag for columns

### ISSUE THREAD

**Issue by jpechane** [eulerto/wal2json#44]
When one is building an Avro schema for the events it might be important to distinguish between optinal and non-optional fields for downstream clients. Would it be possible to add a flag to columns that they are optional?

Thanks!

**Comment by eulerto** [comment]
Describe non-optional. With a not null constraint? Why is it important?

**Comment by jpechane** [comment]
Ah, sorry, yeah I meant `NOT NULL` constraint. If one builds an Avro (or similar) schema  out of the data it might be useful do indicate whether a field can contain a `null` value o not.

**Comment by eulerto** [comment]
@jpechane I've added support for not-null constraints. I'll appreciate if you could test this feature.

**Comment by jpechane** [comment]
Works like a charm, thanks a lot!
