### ISSUE TITLE
Add parameter to filter on table name

### ISSUE THREAD

**Issue by notxcain** [eulerto/wal2json#48]
I see one of the use cases is to replicate a single table with known data schema to Kafka topic.
What do you thing about adding `table` parameter to be used as a filter on relation name?
Maybe there is some other way?

UPD: I forgot to add that schema also should be filtered.

**Comment by rcoup** [comment]
@notxcain maybe something more flexible?

eg. `filter=myschema.mytable1,myschema.mytable2,myschema2.*`
A comma-separated list of `{schema}.{table}` identifiers, or `*` as a table identifier to indicate all tables in the specified schema. Use [quoted identifiers](https://www.postgresql.org/docs/9.6/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS) (eg. `filter="my#schema"."my""weird,table.name",otherschema.othertable` if the value isn't a standard SQL identifier (ie. matches `[a-z][a-z0-9\$_]+` ).

**Comment by rcoup** [comment]
(this probably isn't too complex, Postgres has a bunch of parsing utility functions)

**Comment by notxcain** [comment]
@rcoup thanks for suggestions, I'll take a look :)

**Comment by igouss** [comment]
I would be interested in it too. Seems that it was implemented in a fork https://github.com/goldfix/wal2json/commit/3e8e6db4ba6585ebb453e5f9d9d7ad42b912c2c2

**Comment by eulerto** [comment]
AFAICS this filter mechanism is too fragile. I've added a different implementation (cf 409fcff4478743d161eb0358d26930773335767a) that takes care of special cases (spaces, single quotes, commas, periods) too. I also used the same notation @rcoup said a few comments above (*.foo means table foo in all schemas and bar.* means all tables in schema bar).

**Comment by OndraZizka** [comment]
How is this implemented in the end? I can't find the syntax of `filter-tables`.

**Comment by eulerto** [comment]
@OndraZizka Don't comment on closed issue. Instead, open a new one. Did you read the README?
