### ISSUE TITLE
Clarify what's the encoding for JSON messages

### ISSUE THREAD

**Issue by gunnarmorling** [eulerto/wal2json#57]
Hi, we're seeking some clarity on the encoding used for sending the messages by wal2json. More specifically, is it safe to assume that the bytes can be interpreted using UTF-8?

**Comment by rcoup** [comment]
@gunnarmorling wal2json sets [`OUTPUT_PLUGIN_TEXTUAL_OUTPUT`](https://www.postgresql.org/docs/9.6/static/logicaldecoding-output-plugin.html#LOGICALDECODING-OUTPUT-MODE), so AFAIK it's in the server's encoding.

https://github.com/eulerto/wal2json/pull/40 discusses a couple of other quirks.

**Comment by eulerto** [comment]
@gunnarmorling From the PostgreSQL manual:

> PostgreSQL allows only one character set encoding per database. It is therefore not possible for the JSON types to conform rigidly to the JSON specification unless the database encoding is UTF8. Attempts to directly include characters that cannot be represented in the database encoding will fail; conversely, characters that can be represented in the database encoding but not in UTF8 will be allowed.

**Comment by gunnarmorling** [comment]
@eulerto, that text above applies to JSONB-typed columns, right? So unless I'm mistaken, the wal2json plug-in could still use any other encoding? As per @rcoup, it's the server's encoding. So I suppose we can query the server for that and use the server encoding when parsing incoming messages.

We'll have to see though how that works with Jackson which we use as a parser; I'm not sure whether it supports any encodings other than UTF-8/16/32.

**Comment by eulerto** [comment]
> @eulerto, that text above applies to JSONB-typed columns, right? So unless I'm mistaken, the wal2json plug-in could still use any other encoding? As per @rcoup, it's the server's encoding. So I suppose we can query the server for that and use the server encoding when parsing incoming messages.

That is not limited to JSONB. It is valid for JSON data types. I said that because we use the same API/rules as JSON data types. Hence, this difference in the encoding between JSON standard and Postgres is also valid for wal2json.

> We'll have to see though how that works with Jackson which we use as a parser; I'm not sure whether it supports any encodings other than UTF-8/16/32.

server_encoding is available while establishing a connection.
