### ISSUE TITLE
Table whitelist

### ISSUE THREAD

**Issue by Fxlr8** [eulerto/wal2json#58]
Hi, thanks for the `filter-tables` feature. I tried it today and it works fine, despite the fact, that it works like a blacklist. I have a ton of tables in my database, but I only want a couple of them to be streamed. Is there a way to somehow "inverse" that filter and make it work like a whitelist?

**Comment by eulerto** [comment]
@Fxlr8 Done in commit d13e74940982370a96f3d62ba9e47a5264eb96af. I decided to use `add-tables` as a parameter name. I appreciate if you can test it.

**Comment by Fxlr8** [comment]
@eulerto, tested, works perfectly. What about a combination of `filter-tables` and  `add tables` options? What is the default behavior?

**Comment by eulerto** [comment]
@Fxlr8 The `add-tables` defaults to all tables. The `filter-tables` defaults to nothing. Hence, by default all tables will be considered. If you specify `add-tables` only the selected tables will be considered. If you specify `filter-tables` only the selected tables will be filtered. Let's say you want all tables in schema `foo` except table `foo.bar` then:

`add-tables='foo.*' filter-tables='foo.bar'`

**Comment by Fxlr8** [comment]
@eulerto, if you don't mind, I can update the readme to document this feature
