### ISSUE TITLE
Json without terminating line

### ISSUE THREAD

**Issue by pslavov** [eulerto/wal2json#6]
Hi,
I noticed that sometimes json is not terminated with the final line "]}". After the final change array element I have directly a line similar to this: 
'{"xid":000000,"change":['
and next the other changes and eventually the json terminating line.
This makes json validation more difficult.

**Comment by eulerto** [comment]
I can't reproduce what you described. Can you provide a test case? Are you using the last version? Are you using options (such as write-in-chunks)?

**Comment by pslavov** [comment]
Sorry by the long time no answer.
I now can say that when you turn of write in chunks I had not problem with formating.
But there is another problem. when you have a somewhat big transaction and the string  buffer is filled and it crashes:
pg_recvlogical: unexpected termination of replication stream: ERROR:  out of memory
DETAIL:  Cannot enlarge string buffer containing 1073741191 bytes by 666 more bytes.
CONTEXT:  slot "dwh_sync_slot", output plugin "wal2json", in the change callback, associated LSN DBB/74F71440
pg_recvlogical: disconnected; waiting 5 seconds to try again
I guess this is distribution related, but haven't see how to fix this yet.
I wanted to ask you have you seen this before and how to fix?
I am using Ubuntu Server 14.04.3 LTS with Postgres 9.4.5-1.pgdg14.04+1

thanks

**Comment by eulerto** [comment]
AFAICS, this is a wal2json limitation. I'm using the StringInfo API (src/backend/lib/stringinfo.c) and the string buffer limit is 1GB (cf. MaxAllocSize at include/utils/memutils.h). New code is necessary to support more than 1 GB buffer allocation.

Are you sure you want to accumulate more than 1 GB in transactions?

**Comment by pslavov** [comment]
Hi,
Sadly I am sure that I will have a big volume for single transaction. 
Also logical string generated by any plugin is x2 .. x3 or more in size comparing to the real transaction size, which I think is normal. 
But I don't understand - are you sayng that filled by 1 transaction or multiple transactions ?
Also do you think if I use chunks this problem will not appear ?

**Comment by eulerto** [comment]
Filled by a single transaction (because data is written at commit time anyway). If you use chunks, it can happen only if a single change (command) has more than 1 GB.

**Comment by pslavov** [comment]
hi,
I managed to work around all the limitations and I can say that plugin is working good.
Only one question maybe not related:
When I receive the stream I can see that only sometimes I get the transaction in mixed order - 
first I get transaction id   180670078 then 180670081 then 180670080  then 180670079  then 180670082. 
Before and after the sequence of the transactions is in the right order.
So - can this be from the plugin and did you see it before ?

**Comment by eulerto** [comment]
The order does not come from the plugin. Transaction ids are assigned in time order. However, transactions could not be committed in time order. It means that txid 123 could be committed after txid 456 (e.g. long running transactions). txid 456 will be streamed before txid 123. Take a look at include-timestamp option.

**Comment by pslavov** [comment]
ahaa, of course  - this make sense.
I will close this ticket then, this was very helpful.
 
Thanks!
