### ISSUE TITLE
pg_recvlogical: could not clear search_path: ERROR:  syntax error

### ISSUE THREAD

**Issue by TurboChang** [eulerto/wal2json#61]
I am having problems with "**pg_recvlogical: could not clear search_path: ERROR:  syntax error**" on postgresql 9.6.8. Can anyone tell me how to solve it? Thank you

**Comment by TurboChang** [comment]
I only encountered the above problem after executing "pg_recvlogical -d postgres --slot test_slot --create-slot -P wal2json -p 5432 -U postgres"

**Comment by TurboChang** [comment]
This is my related configuration：
postgresql.conf:
shared_preload_libraries = 'decoderbufs,wal2json'
wal_level = logical
max_wal_senders = 8
wal_keep_segments = 4
wal_sender_timeout = 60s
max_replication_slots = 4

pg_hba.conf:
host    all             all             0.0.0.0/0               trust
host    replication     all             192.168.1.43/32         trust
host    replication     all             192.168.1.43/32         md5
host    replication     all             127.0.0.1/32            md5
host    replication     all             0.0.0.0/0               md5
local   replication     postgres                                trust

**Comment by eulerto** [comment]
@TurboChang It seems a bug in 9.6.8. Use 9.6.7.

**Comment by TurboChang** [comment]
@eulerto OK, let me try, please wait. thank u.

**Comment by eulerto** [comment]
@TurboChang If you want to compile 9.6 from git (REL9_6_STABLE), the fix is already there. If not, use 9.6.7 and then wait for 9.6.9. Another alternative is to apply just the commit 59743deca9a19126ad711874b05c88ab6a59fc47 in 9.6.8 and build a custom version.
