### ISSUE TITLE
Possible to ignore tables w/o PK?

### ISSUE THREAD

**Issue by bwolin** [eulerto/wal2json#64]
Hi,

We are testing this plugin and got tons of log warnings ( > 1M lines) all referring to the same table from the output plugin due to a table without a PK. The table in question, isn't one that we are interested in changes from and is not part of the list we pass into the "add-tables" parameter when we connect. 

Is it possible to ignore changes we're not interested in?

Thanks for any thoughts on this.

Connection request:

>    PGReplicationStream stream =
                replConnection.getReplicationAPI()
                        .replicationStream()
                        .logical()
                        .withSlotName("app_decoder_slot")
                        .withSlotOption("add-tables", subscribedTables.join(','))
                        .withSlotOption("include-unchanged-toast", false)
                        .withStatusInterval(20, TimeUnit.SECONDS)
                        .start();

Sample from log output
> 
... ] 82 WARNING:  table "domains_290906" without primary key or replica identity is nothing
... ] 83 CONTEXT:  slot "cache_decoder_slot", output plugin "wal2json", in the change callback, associated LSN 3D13/A20D2B60
... ] 84 WARNING:  table "domains_290906" without primary key or replica identity is nothing
... ] 85 CONTEXT:  slot "cache_decoder_slot", output plugin "wal2json", in the change callback, associated LSN 3D13/A20D2C30
... ] 86 WARNING:  table "domains_290906" without primary key or replica identity is nothing
... ] 87 CONTEXT:  slot "cache_decoder_slot", output plugin "wal2json", in the change callback, associated LSN 3D13/A20D2D00
... ] 88 WARNING:  table "domains_290906" without primary key or replica identity is nothing
... ] 89 CONTEXT:  slot "cache_decoder_slot", output plugin "wal2json", in the change callback, associated LSN 3D13/A20D2DC8
... ] 90 WARNING:  table "domains_290906" without primary key or replica identity is nothing

**Comment by eulerto** [comment]
It seems to be an oversight at commits (409fcff4478743d161eb0358d26930773335767a and d13e74940982370a96f3d62ba9e47a5264eb96af) that added selective options. Commit 01c5c1ec37b2c27baf00649c028b03936427596a moves the sanity checks a few lines above, hence, avoid to check unsolicited tables.

**Comment by bwolin** [comment]
Thanks for the quick response! I'll get this applied and validated today.
