### ISSUE TITLE
Alpine Linux PostgreSQL Docker image: wal2json.so: __snprintf_chk: symbol not found

### ISSUE THREAD

**Issue by OndraZizka** [eulerto/wal2json#68]
I have compiled wal2json against PostgreSQL 9.5, in Docker container of `postgres:9.5`.  
Then I am trying to load the plugin in PostgreSQL 9.5, again, Docker container, `postgres:9.5-alpine`.   
But here is what I get after `SELECT * FROM pg_create_logical_replication_slot('export5lot', 'wal2json');`:

> ERROR: could not load library "/usr/local/lib/postgresql/wal2json.so": Error relocating /usr/local/lib/postgresql/wal2json.so: __snprintf_chk: symbol not found

This is due to the Alpine Linux using `musl` instead of `glibc`.

I'm not quite sure what to do about it. It's been some time since my last C project.  
Could you please see if there's a way to get around that? Perhaps some flag to use something else than `__snprintf_chk` when building for Alpine?

**Comment by eulerto** [comment]
What are the steps to compile wal2json?

> ERROR: could not load library "/usr/local/lib/postgresql/wal2json.so": Error relocating /usr/local/lib/postgresql/wal2json.so: __snprintf_chk: symbol not found

It seems something wrong with your OS, no?

> Are there any compiled builds with static linking?

Extensions are not linked statically to Postgres.

**Comment by OndraZizka** [comment]
> What are the steps to compile wal2json?
### Wal2json: https://github.com/eulerto/wal2json

Wal2json: https://github.com/eulerto/wal2json

    sudo apt install libpq-dev        
    sudo apt install postgresql-common
    sudo apt install postgresql-server-dev-all
    
    git clone https://github.com/eulerto/wal2json.git
    cd wal2json
    PATH=`which pg_config`:$PATH
    USE_PGXS=1 make
    #USE_PGXS=1 make install
    chmod a+rx wal2json.so
    sudo cp wal2json.so /usr/local/lib/postgresql

> It seems something wrong with your OS, no?
Doesn't seem so, all else works fine. It's a standard Ubuntu 18.04.

> Extensions are not linked statically to Postgres.
I meant to compile the `.so` statically with it's dependencies.

**Comment by OndraZizka** [comment]
I forgot. I am actually running PostgreSQL in Alpine Linux based Docker container, and the issue is that you depend on `glibc` but Alpine has `musl`.

**Comment by eulerto** [comment]
I'm not sure PostgreSQL works with `musl` (I've never tried). I found other reports from this same error message.

**Comment by OndraZizka** [comment]
PostgreSQL works fine on Alpine, there is an official Docker image:
https://hub.docker.com/r/library/postgres/tags/

**Comment by OndraZizka** [comment]
I recalled `ldd`. Here's a list of what's missing. I think there's too much to get rid of `glibc`.

> $ ldd /usr/local/lib/postgresql/wal2json.so 
>        ldd (0x7ffade911000)
>        libc.so.6 => ldd (0x7ffade911000)
> Error relocating /usr/local/lib/postgresql/wal2json.so: palloc0: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: __snprintf_chk: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: pg_lsn_out: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: parse_bool: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: pg_strncasecmp: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: nocachegetattr: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: CurrentMemoryContext: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: OidOutputFunctionCall: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: RelationIdGetRelation: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: OutputPluginWrite: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: lappend: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: ReleaseSysCache: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: elog_finish: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: initStringInfo: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: AllocSetContextCreate: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: list_free_deep: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: text_to_cstring: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: errstart: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: OutputPluginPrepareWrite: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: appendStringInfoChar: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: appendStringInfo: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: get_namespace_name: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: pg_detoast_datum: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: TopMemoryContext: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: escape_json: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: MemoryContextDelete: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: pstrdup: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: RelationClose: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: elog_start: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: format_type: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: getTypeOutputInfo: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: SearchSysCache: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: errmsg: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: timestamptz_to_str: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: DirectFunctionCall2Coll: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: errfinish: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: appendStringInfoString: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: DirectFunctionCall1Coll: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: RelationGetIndexList: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: heap_getsysattr: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: MemoryContextReset: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: pfree: symbol not found
Error relocating /usr/local/lib/postgresql/wal2json.so: errcode: symbol not found

**Comment by OndraZizka** [comment]
Seems like I am in a dead end with Alpine: https://github.com/gliderlabs/docker-alpine/issues/149

**Comment by OndraZizka** [comment]
I have tried to install like it's done in this Dockerfile: https://github.com/jeanblanchard/docker-alpine-glibc/blob/master/Dockerfile
Still no success.

**Comment by dmt-xo** [comment]
I am also facing the similar issue. 
I am running postgres DB as a container on alphine linux.
I am also getting into the similar issue.
Please guide me how to resolve this issue

**Comment by cjbottaro** [comment]
Alpine is becoming (or maybe already is) the standard for running Docker containers. In dev, prod, and everywhere in between. There are official Postgres Docker images for Alpine. It seems that this should build on officially supported distros.

**Comment by cjbottaro** [comment]
This actually works totally fine with the official Postgres Alpine image. Here's a Dockerfile that uses the official image to build/install wal2json:
```Dockerfile
FROM postgres:10.5-alpine AS builder

RUN apk add --no-cache build-base git
RUN git clone https://github.com/eulerto/wal2json.git
WORKDIR wal2json
RUN USE_PGXS=1 make && make install

FROM postgres:10.5-alpine
COPY --from=builder /wal2json/wal2json.so /usr/local/lib/postgresql/
```
Works with https://github.com/disneystreaming/pg2k4j (which relies on this plugin).

**Comment by arajkumar** [comment]
> ```dockerfile
> RUN USE_PGXS=1 make && make install
> ```

In the latest versions, disable the llvm if you see errors related to clang or llvm.

```
RUN make with_llvm=no && make with_llvm=no install
```
