### ISSUE TITLE
Previous value for update statement

### ISSUE THREAD

**Issue by Gordiychuk** [eulerto/wal2json#7]
Is it available get by update statement previous value in result diff? For example next queries 
```sql
create table test_table(id NUMERIC PRIMARY KEY, value VARCHAR(200));
insert into test_table(id, value) values(1, 'original');
update test_table set value = 'modified' where id = 1;
```
generate next diff
```json
{
	"xid": 8273,
	"change": [
		{
			"kind": "insert",
			"schema": "public",
			"table": "test_table",
			"columnnames": ["id", "value"],
			"columntypes": ["numeric", "varchar"],
			"columnvalues": [1, "original"]
		}
	]
}
{
	"xid": 8274,
	"change": [
		{
			"kind": "update",
			"schema": "public",
			"table": "test_table",
			"columnnames": ["id", "value"],
			"columntypes": ["numeric", "varchar"],
			"columnvalues": [1, "modified"],
			"oldkeys": {
				"keynames": ["id"],
				"keytypes": ["numeric"],
				"keyvalues": [1]
			}
		}
	]
}
```

It not allow propagate changes to external system. For example tables can be connected to one document and send to elasticsearch. After update some reference field we should invalidate previous value(it can be back-reference)

**Comment by eulerto** [comment]
In your example, no. What you want is controlled by REPLICA IDENTITY and the default is to include **only** old values from the primary key. If you want **all** of the old values, you must change table replica identity.

euler=# create table test_table(id NUMERIC PRIMARY KEY, value VARCHAR(200));
CREATE TABLE
euler=# alter table test_table replica identity full;
ALTER TABLE
euler=# insert into test_table(id, value) values(1, 'original');
INSERT 0 1
euler=# update test_table set value = 'modified' where id = 1;
UPDATE 1
euler=# SELECT * FROM pg_logical_slot_get_changes('regression_slot', NULL, NULL);
 location  |  xid  |                                                                                       
                                    data                                                                   
                                                         
-----------+-------+---------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------
---------------------------------------------------------
 0/9EC1230 | 14262 | {"xid":14262,"change":[
 0/9EC9AF8 | 14262 | ]}
 0/9EC9B60 | 14263 | {"xid":14263,"change":[
 0/9EC9C98 | 14263 | ]}
 0/9EC9CD0 | 14264 | {"xid":14264,"change":[
 0/9EC9CD0 | 14264 | {"kind":"insert","schema":"public","table":"test_table","columnnames":["id","value"],"
columntypes":["numeric","varchar"],"columnvalues":[1,"original"]}
 0/9EC9DD8 | 14264 | ]}
 0/9EC9EB8 | 14265 | {"xid":14265,"change":[
 0/9EC9EB8 | 14265 | {"kind":"update","schema":"public","table":"test_table","columnnames":["id","value"],"
columntypes":["numeric","varchar"],"columnvalues":[1,"modified"],"oldkeys":{"keynames":["id","value"],"keyt
ypes":["numeric","varchar"],"keyvalues":[1,"original"]}}
 0/9EC9FC8 | 14265 | ]}
(10 registros)

**Comment by Gordiychuk** [comment]
Thanks

**Comment by OndraZizka** [comment]
Thanks! This would be great to have in the main README.md.
