### ISSUE TITLE
 Add per-transaction unique number to each change

### ISSUE THREAD

**Issue by OndraZizka** [eulerto/wal2json#70]
Hi, we use wal2json to transfer incremental changes to an OLAP server (SnowFlake).
It's done in a batch after some period (nightly).
During the day, one table row may change several times.
By SnowFlake import, the changes are considered as a set, not an ordered list, so the duplications may cause the earlier change override the former. For instance:

```
START TRANSACTION;
UPDATE myTable2 SET name = 'Update AA' WHERE id = 401;
UPDATE myTable2 SET name = 'Update BB' WHERE id = 401;
COMMIT;
```
Leads to:
```
{"xid":1074,"timestamp":"2018-07-18 17:49:54.719475+02","change": [
  {"kind":"update","table":"mytable2","columnnames":["id","name","age"],"columnvalues":[401,"Update AA",20],"oldkeys":{"keynames":["id"],"keyvalues":[401]}},
  {"kind":"update","table":"mytable2","columnnames":["id","name","age"],"columnvalues":[401,"Update BB",20],"oldkeys":{"keynames":["id"],"keyvalues":[401]}}
]}
```
It would be great if `wal2json` could add a number to each change

```
{"xid":1074,"timestamp":"2018-07-18 17:49:54.719475+02","change": [
  {"sn":1, "kind":"update","table":"mytable2","columnnames":["id","name","age"],"columnvalues":[401,"Update AA",20],"oldkeys":{"keynames":["id"],"keyvalues":[401]}},
  {"sn":12 "kind":"update","table":"mytable2","columnnames":["id","name","age"],"columnvalues":[401,"Update BB",20],"oldkeys":{"keynames":["id"],"keyvalues":[401]}}
]}
```
Thanks for considering.

**Comment by eulerto** [comment]
Why don't you use parameter `include-xids` or `include-timestamp`?

**Comment by OndraZizka** [comment]
Good point. I assumed that `xid` can be the same for two changes in the same row. That's not correct?

**Comment by OndraZizka** [comment]
I have updated the description. But what is really needed I think is to have one change per row. That's a different feature request, so if you don't mind, I'll create another one, which would actually better match the OLAP scenario. This one is still valid though.

**Comment by eulerto** [comment]
Why don't you use the **change** instead of **rows** for your set? Change already has identification (xid, timestamp).

**Comment by OndraZizka** [comment]
Because the OLAP system takes the import entry by entry, and the entry contains multiple changes Iterating the list of changes,a challenge for the limited SQL subset.

**Comment by eulerto** [comment]
**change** is an ordered collection of values (aka **array**). What is the difficulty in iterating over it? Did you consider **json_to_recordset** function?

**Comment by OndraZizka** [comment]
`json_to_recordset` is PostgreSQL. The target OLAP is SnowFlake.

**Comment by eulerto** [comment]
It seems SnowFlake supports transformation [1]. Doesn't it solve your problem?

[1] https://docs.snowflake.net/manuals/user-guide/data-load-transform.html

**Comment by OndraZizka** [comment]
Unfortunately, not. What you found is what we use, but the imports don't even support a full SQL SELECT functionality.

**Comment by eulerto** [comment]
Commit 1b0cbac484f4fe5db80445f6721957511b4de7b7 added a new format.
