### ISSUE TITLE
Option for a "column":"value" data structure

### ISSUE THREAD

**Issue by OndraZizka** [eulerto/wal2json#71]
Currently, the output data structure is:

    {"change":[{"kind":"update","table":"mytable2",
        "columnnames":["id","name"],
        "columnvalues":[400,"Update 1"],
        "oldkeys":{"keynames":["id"],"keyvalues":[400]}}]
    }

For postprocessing purposes, it would be more appropriate to have this format:

    {"change":[{"kind":"update","table":"mytable2",
        "changes":{"id":400, "name":"Update 1"},
        "oldkeys":{"id":400}}]
    }

I suggest this could be an option

    changes-data-structure = two-arrays | key-value-hash

Thanks for considering.

**Comment by eulerto** [comment]
Commit 1b0cbac484f4fe5db80445f6721957511b4de7b7 added a new format that has exact what you proposed here.
