### ISSUE TITLE
"One change per row" output mode

### ISSUE THREAD

**Issue by OndraZizka** [eulerto/wal2json#72]
We use `wal2json` to do daily batch of incremental updates of an OLAP db (SnowFlake).
The way the JSON is consumed is that the JSON structure is loaded by a SQL function as a table with a single column and one table row per text line; And then accessed using a JSON-parsing SQL functions.

Having multiple changes in a single text line makes processing it quite difficult - it is necessary (if not impossible) to iterate over the `changes: [...]` array.
```
{"xid":1074,"timestamp":"2018-07-18 17:49:54.719475+02","change": [
  {"kind":"update","table":"mytable2","columnnames":["id","name","age"],"columnvalues":[401,"Update AA",20],"oldkeys":{"keynames":["id"],"keyvalues":[401]}},
  {"kind":"update","table":"mytable2","columnnames":["id","name","age"],"columnvalues":[401,"Update BB",20],"oldkeys":{"keynames":["id"],"keyvalues":[401]}}
]}
```
It would relieve a lot of work if the `wal2json` plugin could optionally print a single change ,per JSON entry like this:  `one-change-per-entry = true` would lead to:
```
{"xid":1074,"timestamp":"2018-07-18 17:49:54.719475+02","change": 
  {"kind":"update","table":"mytable2","columnnames":["id","name","age"],"columnvalues":[401,"Update AA",20],"oldkeys":{"keynames":["id"],"keyvalues":[401]}}
}

{"xid":1074,"timestamp":"2018-07-18 17:49:54.719475+02","change": 
  {"kind":"update","table":"mytable2","columnnames":["id","name","age"],"columnvalues":[401,"Update BB",20],"oldkeys":{"keynames":["id"],"keyvalues":[401]}}
}
```
Along with #70, this would still keep each entry uniquely identifiable:
```
{"xid":1074, "sn":1, ... }
{"xid":1074, "sn":2, ... }
```

This way, feeding the data to the OLAP like SnowFlake would need no pre-processing, which would be a big improvement.

Thanks for considering.

**Comment by igouss** [comment]
write-in-chunks: write after every change instead of every changeset. Default is false.

**Comment by eulerto** [comment]
I wouldn't like to have multiple formats. I wouldn't like to change wal2json format unless there is a **strong** argument against the actual format. You are the first person in 4 years that are asking for such format change. I also don't know why you can't use and **ordered** JSON array ("change") to determine the row ordering and use `xid` or `timestamp` to identify each transaction (which must be serially processed). I bet some JSON functions can extract row data.

**Comment by OndraZizka** [comment]
The strong argument is that it needs preprocessing if you need to feed it to a RDBMS.
Here's the ideal output, covering #70, #71, #72:
```
START TRANSACTION;UPDATE myTable2 SET name = 'Update AA' WHERE id = 401;
UPDATE myTable2 SET name = 'Update BB' WHERE id = 401;
COMMIT;
START TRANSACTION;
INSERT INTO myTable2 (name) VALUES ('Inserted');
DELETE FROM myTable2 WHERE name = 'Inserted';
COMMIT;
```

```
{"xid":1075, "table":"mytable2", "newRow":{,"id":401,"name":"Update AA","age":20} }
{"xid":1075, "table":"mytable2", "newRow":{,"id":401,"name":"Update BB","age":20} }
{"xid":1075, "table":"mytable2", "newRow":{,"id":567,"name":"Inserted","age":20} }
{"xid":1075, "table":"mytable2", "deletedRow":{,"id":567} }
{"xid":1076, "table":"mytable2", "newRow":{,"id":401,"name":"Update AA","age":20} }
{"xid":1076, "table":"mytable2", "newRow":{,"id":401,"name":"Update BB","age":20} }
{"xid":1076, "table":"mytable2", "newRow":{,"id":568,"name":"Inserted","age":20} }
{"xid":1076, "table":"mytable2", "deletedRow":{,"id":568} }```

**Comment by OndraZizka** [comment]
I did this transformation using jq, and the performance is terrible - around 1000x slower than without it.
I understand you don't like the idea now, that's ok. We might fork it. Just in case you changed your mind, how would you approach such change? So I can follow that way and perhaps you'll merge somewhere in the future.

**Comment by bryanck** [comment]
We would very much like to see this change merged in, we ended up forking wal2json and adding row-per-change (among other changes like support for different replica identities). Having a row per operation fits very well with streaming changes as events into something like Kafka.

**Comment by eulerto** [comment]
Commit 1b0cbac484f4fe5db80445f6721957511b4de7b7 added a new format.
