### ISSUE TITLE
Guidance using wal2json on AWS?

### ISSUE THREAD

**Issue by nasajoey** [eulerto/wal2json#75]
AWS RDS newbie here.

Trying to follow [this tutorial](https://aws.amazon.com/blogs/database/stream-changes-from-amazon-rds-for-postgresql-using-amazon-kinesis-data-streams-and-aws-lambda/) on streaming data from Postgres RDS:

It relies on wal2json.

The [RDS docs say](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.FeatureSupport.Extensions.96x) that wal2json is supported in the version of Postgres I am running (9.6.9):

When running `show rds.extensions;` I get no wal2json:

> address_standardizer,address_standardizer_data_us,bloom,btree_gin,btree_gist,chkpass,citext,cube,dblink,dict_int,dict_xsyn,earthdistance,fuzzystrmatch,hll,hstore,hstore_plperl,intagg,intarray,ip4r,isn,log_fdw,ltree,orafce,pgaudit,pgcrypto,pgrouting,pgrowlocks,pgstattuple,pg_buffercache,pg_freespacemap,pg_hint_plan,pg_prewarm,pg_repack,pg_stat_statements,pg_trgm,pg_visibility,plcoffee,plls,plperl,plpgsql,pltcl,plv8,postgis,postgis_tiger_geocoder,postgis_topology,postgres_fdw,prefix,sslinfo,tablefunc,test_parser,tsearch2,tsm_system_rows,tsm_system_time,unaccent,uuid-ossp

I can't find any instructions on getting wal2json enabled on RDS, but everywhere says it should be possible.

Any guidance on getting it working on RDS? I feel like I must be missing something obvious.

Thanks in advance.

**Comment by nasajoey** [comment]
Well, I just kept going with the tutorial and stuff worked.  Still a little confused as to where wal2json lives and how it got wherever it lives.  I'm OK with confusion if still getting results.

**Comment by lievertz** [comment]
Comment for history: I found this a bit later after looking around at a similar topic. Despite the eulerto github page (colloquially?) calling wal2json an extension, it indeed does not show up in `pg_extension`. You will only find it referenced by the column `plugin` on the view `pg_replication_slots` (or the function `pg_get_replication_slots()`). And if you are bothering to do so, you might also want to look at the `active` boolean to see if the replication slot you are attempting to use this plugin on is active or not.
