### ISSUE TITLE
when specifying options, changes is empty?

### ISSUE THREAD

**Issue by bwalsh** [eulerto/wal2json#77]
Hi.  Thanks for a great piece of software.  Very useful.

I've been using it with no problem.  However, when I add options, the changes returned is empt?

```
    cur.start_replication(slot_name=slot_name, decode=True)

<ReplicationMessage object at 0x7fcdeb874ca8; data_size: 990; data_start: 0/28b8e18; wal_end: 0/28b8e18; send_time: 0>
{"change":[{"kind":"update", ...

```

```
    replication_options = {'add-tables': [configs['queries'].keys()]}
    cur.start_replication(slot_name=slot_name, decode=True, options=replication_options)

<ReplicationMessage object at 0x7f94563d6d00; data_size: 13; data_start: 0/28bb5a0; wal_end: 0/28bb5a0; send_time: 0>
{"change":[]}
    
```

**Comment by eulerto** [comment]
@bwalsh Could you provide a test case?

**Comment by bwalsh** [comment]
Thank you for the quick response.

As I was developing a test case, I discovered the problem.  :-)

I was providing an array of strings, e.g ["s1.table1",  "s2.table2"].  The answer was to provide a comma separated list "s1.table1,s2.table2".

That resolved the issue.
