### ISSUE TITLE
Option -write-in-chunks not very practical because it is not parsable

### ISSUE THREAD

**Issue by pbillen** [eulerto/wal2json#84]
Hi,

When enabling the option `write-in-chunks`, I am getting an event for every change, which is as expected. However, the corresponding JSON is not parsable:

    ,{"kind":"insert","schema":"public","table":"bla","columnnames":["i","t"],"columntypes":["integer","timestamp with time zone"],"columnvalues":[9004118,"2018-10-30 15:42:53.876841+00"]}

Note the leading `,`. This has been tested by `pg_recvlogical`.

I would say this is a bug? That is, I would assume that each change can be processed in an ad hoc-fasion, regardless of it being part of a bigger change set.

This has been tested with the current head of the `master` branch.

Thanks!

**Comment by eulerto** [comment]
@pbillen Read issue #4. Each change is **not** a valid JSON. The `write-in-chunks` parameter is to work around a postgres memory limitation for long transactions (see issue #46, for example).

**Comment by pbillen** [comment]
Thanks for feedback.

Doesn't this contradict https://github.com/eulerto/wal2json/issues/17#issuecomment-300045192?

What can the client/consumer do with such invalid payloads? Do we have to `string-concat` until we received the last one? In that case, we are just propagating the memory issues downchain?

**Comment by eulerto** [comment]
> Doesn't this contradict #17 (comment)?

No, it doesn't. The **whole** transaction is a valid JSON; each change (while `write-in-chunks = 1`) is not.

> What can the client/consumer do with such invalid payloads? Do we have to string-concat until we received the last one?

Hold until you have the whole transaction or process while receiving the changes.

>  In that case, we are just propagating the memory issues downchain?

It depends on the way you will consume the information.

**Comment by pbillen** [comment]
Thanks again!

I might very likely be missing something obvious, but how can we consume/process if we cannot parse the payload? All we can do is:

- hackery and remove the leading `,`
-`concat`/`append` to an intermediate memory/file buffer and very likely end up with a ginormous JSON object which might be unparsable due to memory constraints (which is exactly the reason why `write-in-chunks` was introduced)

Could you please elaborate how this would work in practise?

**Comment by eulerto** [comment]
`wal2json` was designed to deliver each transaction at time. As I said `write-in-chunks` was designed to fix a postgres limitation, it is not a each-change-at-time solution.
While we don't have another format (despite what I said in https://github.com/eulerto/wal2json/issues/72#issuecomment-406136624, I'm considering another flexible format whose focus is the changes), the hackery solution `s/^,{/{/` is your best bet.

**Comment by pbillen** [comment]
I am not sure how this answers my concerns.

I certainly agree that the client/consumer must be able to preserve the scope of a transaction. We can use `include-xids` in combination with `-write-in-chunks` for this.

Let me phrase it like this: what do we gain with providing invalid JSON?

Looking forward to the changes you mentioned!

**Comment by pbillen** [comment]
@rcoup Fair enough, that would work; though I can hardly imagine the ugly code to SAX-like parse this. Also, from the moment we encounter a persistent parse error, the slot becomes useless because we lost all context. We do not know if a subsequent payload is still part of the troubled transaction or not, as we cannot evaluate it in vacuum (hackery aside).

A stand-alone message with transaction id + change sequence number does not suffer from this.

**Comment by apopescu-im** [comment]
Just to add my 2¢, we found write-in-chunks essential to what we're doing.  Due to memory limitations many of our transactions couldn't be retrieved without it.  Yes, it would have been easier if individual objects were valid JSON (such as a sequence of <start object><change object><change object>....<end object>), but pre-processing each chunk to detect start/end/change and stripping the comma from changes is working reliably.

In our case the downstream system is tolerant of re-writes so the approach is to peek changes, execute and acknowledge them on the downstream system, then once the end of the change object comes through we get the same changes (to advance the slot) discarding the result.  This means everything is guaranteed to be executed on the downstream, and a mid-set failure causes earlier changes in that set to be re-executed.

**Comment by pbillen** [comment]
This is covered by https://github.com/eulerto/wal2json/pull/110.
