### ISSUE TITLE
Add option to track replication origin and filter out unwanted LSNs

### ISSUE THREAD

**Issue by rafaelthca** [eulerto/wal2json#86]
In multi-master scenarios it would be helpful to be able to filter out LSNs that come from remote nodes.

**Comment by martinmarques** [comment]
How about a `locals_only` boolean GUC, and ignore anything that comes from a different origin. Idea of @bonesmoses.

**Comment by eulerto** [comment]
Commit 9b579240ec8735e762920bdeff8ca02e201bfa03 implemented parameter `filter-origins` that I mentioned in PR #88 . Hence, it is possible to filter by origin.
