### ISSUE TITLE
Data Mismatch/Loss for Postgres Decimal and Numeric datatypes

### ISSUE THREAD

**Issue by reynoldregan** [eulerto/wal2json#90]
If source table has Decimal(20,10) or Numeric(20,10) datatype, data captured is incorrect.
Source table: public.tas1;
Target table: public.tat1;

# select * from  public.tas1;
 id |          col1          
----+------------------------
  0 | -1234567890.1234567890
  1 | -1234567890.1234567890
  2 |  9234567890.1234567890
  3 |  3456789012.3456789012
  4 |  4567890123.4567890123
  5 |  5678901234.5678901234

select * from  public.tat1;
 id |          col1          
----+------------------------
  0 | -1234567890.1234600000
  1 | -1234567890.1234600000
  2 |  9234567890.1234600000
  3 |  3456789012.3456800000
  4 |  4567890123.4567900000

**Comment by eulerto** [comment]
I tested my script with 9.6.11 and latest wal2json. It worked as expected. Are you sure `tas1` and `tat1` have the same schema?
I suggest that you test my script with the latest wal2json (aa4077a6e05ae3ba2995172623b9928a190f1690).

**Comment by reynoldregan** [comment]
working fine
