### ISSUE TITLE
Error Install: wal2json.c:17:33: fatal error: replication/logical.h: No such file or directory

### ISSUE THREAD

**Issue by tigac** [eulerto/wal2json#92]
When I tried to call 
`USE_PGXS=1 make`

I got this message:
`wal2json.c:17:33: fatal error: replication/logical.h: No such file or directory
 #include "replication/logical.h"`

I use Centos 7.5 and Postgreq 10.6

**Comment by eulerto** [comment]
@tigac It seems you don't install `postgresql10-devel`.

**Comment by tigac** [comment]
Hi @eulerto ,

I've installed `postgresql10-devel` but the error still remains. I've installed the `postgresql10-contrib` as well.

inside my /usr/include/pgsql/server/replication/ I only see these files:
- basebackup.h 
- syncrep.h
- walprotocol.h  
- walreceiver.h  
- walsender.h  
- walsender_private.h

Regards

**Comment by eulerto** [comment]
There is something wrong with your OS.

```
# cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 
# rpm -ql postgresql10-devel | grep logical.h
/usr/pgsql-10/include/server/replication/logical.h
# yum repolist | grep pgdg
pgdg10/7/x86_64      PostgreSQL 10 7 - x86_64                                487
```

**Comment by tigac** [comment]
Hi @eulerto 

Sorry for the long silence, I run the commands that you shared and had all the same output.

Do I need to move the downloaded wal2json folder somewhere?

Regards,

**Comment by eulerto** [comment]
@tigac I bet a dime that you have another `pg_config` in your PATH.

```
export PATH=/usr/pgsql-10/bin/:$PATH
echo $PATH
```

**Comment by tigac** [comment]
Holy guacamole, you're spot on @eulerto !

When I type:
`find / -name pg_config`
there are 2 files.

Redirecting the makefile to the correct file fix the issue.

PS:

For those who are facing the same issue, the easiest way to fix this is to edit the Makefile and point the pg_config to the correct path (in my case PG_CONFIG = /usr/pgsql-10/bin/pg_config)

**Comment by eulerto** [comment]
@tigac As I said, the easiest way is to fix your PATH. Make sure the correct `pg_config` is the first in your path.
