### ISSUE TITLE
ERROR: missing chunk number 0 for toast value 55804650 in pg_toast_21513

### ISSUE THREAD

**Issue by murongruomeng** [eulerto/wal2json#95]
We are integrating with kafka and encountered this problem, it blocks  the postgres streaming

**Comment by eulerto** [comment]
@murongruomeng it seems you are using a version before I reverted parameter include-unchanged-toast. Read issue #74.

**Comment by murongruomeng** [comment]
@eulerto but include-unchanged-toast is deprecated now
`else if (strcmp(elem->defname, "include-unchanged-toast") == 0)
		{
			ereport(ERROR,
					(errcode(ERRCODE_INVALID_NAME),
					 errmsg("parameter \"%s\" was deprecated", elem->defname)));
		}`

**Comment by eulerto** [comment]
@murongruomeng Did you read the issue I pointed out? That option is unsafe.
