### ISSUE TITLE
Passing "include-unchanged-toast" makes client fail

### ISSUE THREAD

**Issue by gunnarmorling** [eulerto/wal2json#96]
I saw that the "include-unchanged-toast" was meant to be deprecated, but when starting the replication stream, I'm actually getting a hard error:

```
org.postgresql.util.PSQLException: ERROR: parameter "include-unchanged-toast" was deprecated
Where: slot "debezium", output plugin "wal2json", in the startup callback
```

I.e. it's not really deprecated but really unsupported. Could this be changed to raise a warning only, making it a true deprecation? Otherwise it gets tricky for consumers such as Debezium to support multiple versions of wal2json.

**Comment by eulerto** [comment]
@gunnarmorling Hmmm. Fair enough. Why don't you remove `include-unchanged-toast` from Debezium?

**Comment by gunnarmorling** [comment]
> Why don't you remove include-unchanged-toast from Debezium?

We want to set its value to 0, i.e. disable it (see [DBZ-842](https://issues.jboss.org/browse/DBZ-842). This causes the connector to fail though with newer wal2json versions that removed the option.

**Comment by davecramer** [comment]
@eulerto Surprisingly the plugin still continues merrily on its way even though the rest of the startup parameters may or may not be read. I would think if you are going to fail hard on this parameter you'd want to stop the plugin from actually working.

**Comment by eulerto** [comment]
@davecramer it fails if you passes the deprecated parameter.

```
euler=# CREATE TABLE table2_with_pk (a SERIAL, b VARCHAR(30), c TIMESTAMP NOT NULL, PRIMARY KEY(a, c));
CREATE TABLE
euler=# SELECT 'init' FROM pg_create_logical_replication_slot('test_slot', 'wal2json');
 ?column? 
----------
 init
(1 registro)

euler=# INSERT INTO table2_with_pk (b, c) VALUES('Backup and Restore', now());
INSERT 0 1
euler=# INSERT INTO table2_with_pk (b, c) VALUES('Tuning', now());
INSERT 0 1
euler=# SELECT data FROM pg_logical_slot_get_changes('test_slot', NULL, NULL, 'include-unchanged-toast', '1');
ERROR:  parameter "include-unchanged-toast" was deprecated
CONTEXTO:  slot "test_slot", output plugin "wal2json", in the startup callback
euler=# SELECT data FROM pg_logical_slot_get_changes('test_slot', NULL, NULL);
                                                                                                                            data                                         
                                                                                   
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------
 {"change":[{"kind":"insert","schema":"public","table":"table2_with_pk","columnnames":["a","b","c"],"columntypes":["integer","character varying(30)","timestamp without t
ime zone"],"columnvalues":[1,"Backup and Restore","2019-09-16 22:59:52.627235"]}]}
 {"change":[{"kind":"insert","schema":"public","table":"table2_with_pk","columnnames":["a","b","c"],"columntypes":["integer","character varying(30)","timestamp without t
ime zone"],"columnvalues":[2,"Tuning","2019-09-16 22:59:53.432013"]}]}
(2 registros)

euler=# SELECT 'stop' FROM pg_drop_replication_slot('test_slot');
 ?column? 
----------
 stop
(1 registro)
```

**Comment by davecramer** [comment]
@eulerto thanks for looking into this.
@gunnarmorling  this is contrary to your experience ?

**Comment by raja073** [comment]
Hi, we were doing load test in debezium Aurora postgres connector and the connector failed when I tried to update 1 million records to postgres table in single transition. Error message was:
`Caused by: org.postgresql.util.PSQLException: ERROR: parameter "include-unchanged-toast" was deprecated
  Where: slot "wal2json_<name>", output plugin "wal2json", in the startup callback`
Is it related to the same issue? Is there any workaround for this at the moment?
